steps:
- id: 'fetch_submodules'
  # TODO: for pull requests, the "as-if-merged" version or the PR should be tested first
  name: 'gcr.io/cloud-builders/git'
  args: ['submodule', 'update', '--init']
- id: 'build_artifacts_python'
  name: 'grpctesting/cloud_build_base:9937b7c086937fb5ed5fc987ab445efd193984e1'  # modified version of gcr.io/cloud-builders/docker with some extra dependencies.

  args: ['python', 'tools/run_tests/task_runner.py', '-f', 'artifact', 'linux', 'python', 'cp27-cp27mu', '-j4']

  # run script: grpc/tools/internal_ci/linux/grpc_run_tests_matrix.sh
  #key: "RUN_TESTS_FLAGS"
  #value: "-f basictests linux csharp --inner_jobs 16 -j 2 --internal_ci --bq_result_table aggregate_results"
  env:
    - 'DOCKERHUB_ORGANIZATION=grpctesting'  # needed to prevent re-building images
- id: 'list artifacts'
  name: 'grpctesting/cloud_build_base:9937b7c086937fb5ed5fc987ab445efd193984e1'  # modified version of gcr.io/cloud-builders/docker with some extra dependencies.
  # TODO: include the steps normally done by build_packages
  args: ['ls', '-lR', 'artifacts']
- id: 'prepare_distribtest'
  name: 'grpctesting/cloud_build_base:9937b7c086937fb5ed5fc987ab445efd193984e1'  # modified version of gcr.io/cloud-builders/docker with some extra dependencies.
  # TODO: include the steps normally done by build_packages
  args: ['bash', '-c', 'mkdir -p input_artifacts && cp -r artifacts/python_*/* input_artifacts || true']
- id: 'distribtest_python'
  name: 'grpctesting/cloud_build_base:9937b7c086937fb5ed5fc987ab445efd193984e1'  # modified version of gcr.io/cloud-builders/docker with some extra dependencies.
  args: ['python', 'tools/run_tests/task_runner.py', '-f', 'distribtest', 'linux', 'python', 'jessie', 'x64', '-j4']
  env:
    - 'DOCKERHUB_ORGANIZATION=grpctesting'  # needed to prevent re-building images
timeout: 1800s
options:
  machineType: 'N1_HIGHCPU_8'
  logging: GCS_ONLY
#tags: ['basictests', 'csharp', 'linux', 'opt']
artifacts:
  objects:
    location: 'gs://grpc-testing-cloudbuild-public-logs/experimental_build_artifacts/artifacts-$BUILD_ID'
    # note: the directory path of the artifacts is not preserved
    paths: ['artifacts/**/**']
logsBucket: 'grpc-testing-cloudbuild-public-logs/experimental_build_logs'
