%YAML 1.2
--- |
  # Copyright 2016, gRPC authors
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #   http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.

  FROM debian:wheezy

  <%include file="../../apt_get_basic.include"/>
  <%include file="../../python_deps.include"/>
  <%include file="../../cxx_deps.include"/>

  RUN apt-get update && apt-get install -y ${'\\'}
    gcc-4.4 ${'\\'}
    gcc-4.4-multilib ${'\\'}
    g++-4.4 ${'\\'}
    g++-4.4-multilib

  # set up backport to allow installation of Git version > 1.7
  RUN echo "deb http://http.debian.net/debian wheezy-backports main" \
    >/etc/apt/sources.list.d/wheezy-backports.list
  RUN apt-get update -qq
  RUN apt-get -t wheezy-backports install -qq git
  
  RUN wget ${openssl_fallback.base_uri + openssl_fallback.tarball}

  ENV POST_GIT_STEP tools/dockerfile/test/cxx_wheezy_x64/post-git-setup.sh

  <%include file="../../run_tests_addons.include"/>
  # Define the default command.
  CMD ["bash"]
