
%YAML 1.2
--- |
  # Copyright 2019 The gRPC Authors
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.

  <%include file="../../python_stretch.include"/>
  RUN apt-get install -y jq zlib1g-dev libssl-dev

  COPY get_cpython.sh /tmp
  RUN apt-get install -y jq build-essential libffi-dev && ${'\\'}
    chmod +x /tmp/get_cpython.sh && ${'\\'}
    /tmp/get_cpython.sh && ${'\\'}
    rm /tmp/get_cpython.sh

  RUN python3.8 -m ensurepip && ${'\\'}
      python3.8 -m pip install coverage
