source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'gRPC', :path => "../../../.."
pod 'RemoteTest', :path => "../../generated_libraries/RemoteTestClient"

target 'Sample' do
end
