source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'gRPC', :path => "../../../.."
pod 'Route_guide', :path => "protos"

link_with 'Sample', 'SampleTests'

target 'Sample' do
end

target 'SampleTests' do
end
