cc_test(
    name = "alloc_test",
    srcs = ["alloc_test.c"],
    deps = ["//:gpr", "//test/core/util:gpr_test_util"],
)

cc_test(
    name = "avl_test",
    srcs = ["avl_test.c"],
    deps = ["//:gpr", "//test/core/util:gpr_test_util"],
)

cc_test(
    name = "backoff_test",
    srcs = ["backoff_test.c"],
    deps = ["//:gpr", "//test/core/util:gpr_test_util"],
)

cc_test(
    name = "cmdline_test",
    srcs = ["cmdline_test.c"],
    deps = ["//:gpr", "//test/core/util:gpr_test_util"],
)

cc_test(
    name = "cpu_test",
    srcs = ["cpu_test.c"],
    deps = ["//:gpr", "//test/core/util:gpr_test_util"],
)

cc_test(
    name = "env_test",
    srcs = ["env_test.c"],
    deps = ["//:gpr", "//test/core/util:gpr_test_util"],
)

cc_test(
    name = "histogram_test",
    srcs = ["histogram_test.c"],
    deps = ["//:gpr", "//test/core/util:gpr_test_util"],
)

cc_test(
    name = "host_port_test",
    srcs = ["host_port_test.c"],
    deps = ["//:gpr", "//test/core/util:gpr_test_util"],
)

cc_test(
    name = "log_test",
    srcs = ["log_test.c"],
    deps = ["//:gpr", "//test/core/util:gpr_test_util"],
)

cc_test(
    name = "mpscq_test",
    srcs = ["mpscq_test.c"],
    deps = ["//:gpr", "//test/core/util:gpr_test_util"],
)

cc_test(
    name = "murmur_hash_test",
    srcs = ["murmur_hash_test.c"],
    deps = ["//:gpr", "//test/core/util:gpr_test_util"],
)

cc_test(
    name = "percent_encoding_test",
    srcs = ["percent_encoding_test.c"],
    deps = ["//:gpr", "//test/core/util:gpr_test_util"],
)

cc_test(
    name = "slice_buffer_test",
    srcs = ["slice_buffer_test.c"],
    deps = ["//:gpr", "//test/core/util:gpr_test_util"],
)

cc_test(
    name = "slice_test",
    srcs = ["slice_test.c"],
    deps = ["//:gpr", "//test/core/util:gpr_test_util"],
)

cc_test(
    name = "stack_lockfree_test",
    srcs = ["stack_lockfree_test.c"],
    deps = ["//:gpr", "//test/core/util:gpr_test_util"],
)

cc_test(
    name = "string_test",
    srcs = ["string_test.c"],
    deps = ["//:gpr", "//test/core/util:gpr_test_util"],
)

cc_test(
    name = "sync_test",
    srcs = ["sync_test.c"],
    deps = ["//:gpr", "//test/core/util:gpr_test_util"],
)

cc_test(
    name = "thd_test",
    srcs = ["thd_test.c"],
    deps = ["//:gpr", "//test/core/util:gpr_test_util"],
)

cc_test(
    name = "time_test",
    srcs = ["time_test.c"],
    deps = ["//:gpr", "//test/core/util:gpr_test_util"],
)

cc_test(
    name = "tls_test",
    srcs = ["tls_test.c"],
    deps = ["//:gpr", "//test/core/util:gpr_test_util"],
)

cc_test(
    name = "useful_test",
    srcs = ["useful_test.c"],
    deps = ["//:gpr", "//test/core/util:gpr_test_util"],
)
