# GRPC Bazel BUILD file.
# This currently builds C, C++ and Objective-C code.
# This file has been automatically generated from a template file.
# Please look at the templates directory instead.
# This file can be regenerated from the template by running
# tools/buildgen/generate_projects.sh

# Copyright 2015, Google Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#     * Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above
# copyright notice, this list of conditions and the following disclaimer
# in the documentation and/or other materials provided with the
# distribution.
#     * Neither the name of Google Inc. nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

licenses(["notice"])  # 3-clause BSD

package(default_visibility = ["//visibility:public"])




cc_library(
  name = "gpr",
  srcs = [
    "src/core/profiling/timers.h",
    "src/core/support/block_annotate.h",
    "src/core/support/env.h",
    "src/core/support/file.h",
    "src/core/support/murmur_hash.h",
    "src/core/support/stack_lockfree.h",
    "src/core/support/string.h",
    "src/core/support/string_win32.h",
    "src/core/support/thd_internal.h",
    "src/core/support/time_precise.h",
    "src/core/profiling/basic_timers.c",
    "src/core/profiling/stap_timers.c",
    "src/core/support/alloc.c",
    "src/core/support/cmdline.c",
    "src/core/support/cpu_iphone.c",
    "src/core/support/cpu_linux.c",
    "src/core/support/cpu_posix.c",
    "src/core/support/cpu_windows.c",
    "src/core/support/env_linux.c",
    "src/core/support/env_posix.c",
    "src/core/support/env_win32.c",
    "src/core/support/file.c",
    "src/core/support/file_posix.c",
    "src/core/support/file_win32.c",
    "src/core/support/histogram.c",
    "src/core/support/host_port.c",
    "src/core/support/log.c",
    "src/core/support/log_android.c",
    "src/core/support/log_linux.c",
    "src/core/support/log_posix.c",
    "src/core/support/log_win32.c",
    "src/core/support/murmur_hash.c",
    "src/core/support/slice.c",
    "src/core/support/slice_buffer.c",
    "src/core/support/stack_lockfree.c",
    "src/core/support/string.c",
    "src/core/support/string_posix.c",
    "src/core/support/string_win32.c",
    "src/core/support/subprocess_posix.c",
    "src/core/support/sync.c",
    "src/core/support/sync_posix.c",
    "src/core/support/sync_win32.c",
    "src/core/support/thd.c",
    "src/core/support/thd_posix.c",
    "src/core/support/thd_win32.c",
    "src/core/support/time.c",
    "src/core/support/time_posix.c",
    "src/core/support/time_precise.c",
    "src/core/support/time_win32.c",
    "src/core/support/tls_pthread.c",
  ],
  hdrs = [
    "include/grpc/support/alloc.h",
    "include/grpc/support/atm.h",
    "include/grpc/support/atm_gcc_atomic.h",
    "include/grpc/support/atm_gcc_sync.h",
    "include/grpc/support/atm_win32.h",
    "include/grpc/support/cmdline.h",
    "include/grpc/support/cpu.h",
    "include/grpc/support/histogram.h",
    "include/grpc/support/host_port.h",
    "include/grpc/support/log.h",
    "include/grpc/support/log_win32.h",
    "include/grpc/support/port_platform.h",
    "include/grpc/support/slice.h",
    "include/grpc/support/slice_buffer.h",
    "include/grpc/support/string_util.h",
    "include/grpc/support/subprocess.h",
    "include/grpc/support/sync.h",
    "include/grpc/support/sync_generic.h",
    "include/grpc/support/sync_posix.h",
    "include/grpc/support/sync_win32.h",
    "include/grpc/support/thd.h",
    "include/grpc/support/time.h",
    "include/grpc/support/tls.h",
    "include/grpc/support/tls_gcc.h",
    "include/grpc/support/tls_msvc.h",
    "include/grpc/support/tls_pthread.h",
    "include/grpc/support/useful.h",
  ],
  includes = [
    "include",
    ".",
  ],
  deps = [
  ],
)


cc_library(
  name = "grpc",
  srcs = [
    "src/core/security/auth_filters.h",
    "src/core/security/base64.h",
    "src/core/security/credentials.h",
    "src/core/security/handshake.h",
    "src/core/security/json_token.h",
    "src/core/security/jwt_verifier.h",
    "src/core/security/secure_endpoint.h",
    "src/core/security/security_connector.h",
    "src/core/security/security_context.h",
    "src/core/tsi/fake_transport_security.h",
    "src/core/tsi/ssl_transport_security.h",
    "src/core/tsi/transport_security.h",
    "src/core/tsi/transport_security_interface.h",
    "src/core/census/grpc_filter.h",
    "src/core/channel/channel_args.h",
    "src/core/channel/channel_stack.h",
    "src/core/channel/client_channel.h",
    "src/core/channel/client_uchannel.h",
    "src/core/channel/compress_filter.h",
    "src/core/channel/connected_channel.h",
    "src/core/channel/context.h",
    "src/core/channel/http_client_filter.h",
    "src/core/channel/http_server_filter.h",
    "src/core/channel/noop_filter.h",
    "src/core/client_config/client_config.h",
    "src/core/client_config/connector.h",
    "src/core/client_config/lb_policies/load_balancer_api.h",
    "src/core/client_config/lb_policies/pick_first.h",
    "src/core/client_config/lb_policies/round_robin.h",
    "src/core/client_config/lb_policy.h",
    "src/core/client_config/lb_policy_factory.h",
    "src/core/client_config/lb_policy_registry.h",
    "src/core/client_config/resolver.h",
    "src/core/client_config/resolver_factory.h",
    "src/core/client_config/resolver_registry.h",
    "src/core/client_config/resolvers/dns_resolver.h",
    "src/core/client_config/resolvers/sockaddr_resolver.h",
    "src/core/client_config/subchannel.h",
    "src/core/client_config/subchannel_factory.h",
    "src/core/client_config/subchannel_factory_decorators/add_channel_arg.h",
    "src/core/client_config/subchannel_factory_decorators/merge_channel_args.h",
    "src/core/client_config/uri_parser.h",
    "src/core/compression/message_compress.h",
    "src/core/debug/trace.h",
    "src/core/httpcli/format_request.h",
    "src/core/httpcli/httpcli.h",
    "src/core/httpcli/parser.h",
    "src/core/iomgr/closure.h",
    "src/core/iomgr/endpoint.h",
    "src/core/iomgr/endpoint_pair.h",
    "src/core/iomgr/exec_ctx.h",
    "src/core/iomgr/executor.h",
    "src/core/iomgr/fd_posix.h",
    "src/core/iomgr/iocp_windows.h",
    "src/core/iomgr/iomgr.h",
    "src/core/iomgr/iomgr_internal.h",
    "src/core/iomgr/iomgr_posix.h",
    "src/core/iomgr/pollset.h",
    "src/core/iomgr/pollset_posix.h",
    "src/core/iomgr/pollset_set.h",
    "src/core/iomgr/pollset_set_posix.h",
    "src/core/iomgr/pollset_set_windows.h",
    "src/core/iomgr/pollset_windows.h",
    "src/core/iomgr/resolve_address.h",
    "src/core/iomgr/sockaddr.h",
    "src/core/iomgr/sockaddr_posix.h",
    "src/core/iomgr/sockaddr_utils.h",
    "src/core/iomgr/sockaddr_win32.h",
    "src/core/iomgr/socket_utils_posix.h",
    "src/core/iomgr/socket_windows.h",
    "src/core/iomgr/tcp_client.h",
    "src/core/iomgr/tcp_posix.h",
    "src/core/iomgr/tcp_server.h",
    "src/core/iomgr/tcp_windows.h",
    "src/core/iomgr/time_averaged_stats.h",
    "src/core/iomgr/timer.h",
    "src/core/iomgr/timer_heap.h",
    "src/core/iomgr/timer_internal.h",
    "src/core/iomgr/udp_server.h",
    "src/core/iomgr/wakeup_fd_pipe.h",
    "src/core/iomgr/wakeup_fd_posix.h",
    "src/core/iomgr/workqueue.h",
    "src/core/iomgr/workqueue_posix.h",
    "src/core/iomgr/workqueue_windows.h",
    "src/core/json/json.h",
    "src/core/json/json_common.h",
    "src/core/json/json_reader.h",
    "src/core/json/json_writer.h",
    "src/core/proto/load_balancer.pb.h",
    "src/core/statistics/census_interface.h",
    "src/core/statistics/census_rpc_stats.h",
    "src/core/surface/api_trace.h",
    "src/core/surface/byte_buffer_queue.h",
    "src/core/surface/call.h",
    "src/core/surface/call_test_only.h",
    "src/core/surface/channel.h",
    "src/core/surface/completion_queue.h",
    "src/core/surface/event_string.h",
    "src/core/surface/init.h",
    "src/core/surface/server.h",
    "src/core/surface/surface_trace.h",
    "src/core/transport/chttp2/alpn.h",
    "src/core/transport/chttp2/bin_encoder.h",
    "src/core/transport/chttp2/frame.h",
    "src/core/transport/chttp2/frame_data.h",
    "src/core/transport/chttp2/frame_goaway.h",
    "src/core/transport/chttp2/frame_ping.h",
    "src/core/transport/chttp2/frame_rst_stream.h",
    "src/core/transport/chttp2/frame_settings.h",
    "src/core/transport/chttp2/frame_window_update.h",
    "src/core/transport/chttp2/hpack_parser.h",
    "src/core/transport/chttp2/hpack_table.h",
    "src/core/transport/chttp2/http2_errors.h",
    "src/core/transport/chttp2/huffsyms.h",
    "src/core/transport/chttp2/incoming_metadata.h",
    "src/core/transport/chttp2/internal.h",
    "src/core/transport/chttp2/status_conversion.h",
    "src/core/transport/chttp2/stream_encoder.h",
    "src/core/transport/chttp2/stream_map.h",
    "src/core/transport/chttp2/timeout_encoding.h",
    "src/core/transport/chttp2/varint.h",
    "src/core/transport/chttp2_transport.h",
    "src/core/transport/connectivity_state.h",
    "src/core/transport/metadata.h",
    "src/core/transport/stream_op.h",
    "src/core/transport/transport.h",
    "src/core/transport/transport_impl.h",
    "third_party/nanopb/pb.h",
    "third_party/nanopb/pb_common.h",
    "third_party/nanopb/pb_decode.h",
    "third_party/nanopb/pb_encode.h",
    "src/core/census/aggregation.h",
    "src/core/census/context.h",
    "src/core/census/rpc_metric_id.h",
    "src/core/httpcli/httpcli_security_connector.c",
    "src/core/security/base64.c",
    "src/core/security/client_auth_filter.c",
    "src/core/security/credentials.c",
    "src/core/security/credentials_metadata.c",
    "src/core/security/credentials_posix.c",
    "src/core/security/credentials_win32.c",
    "src/core/security/google_default_credentials.c",
    "src/core/security/handshake.c",
    "src/core/security/json_token.c",
    "src/core/security/jwt_verifier.c",
    "src/core/security/secure_endpoint.c",
    "src/core/security/security_connector.c",
    "src/core/security/security_context.c",
    "src/core/security/server_auth_filter.c",
    "src/core/security/server_secure_chttp2.c",
    "src/core/surface/init_secure.c",
    "src/core/surface/secure_channel_create.c",
    "src/core/tsi/fake_transport_security.c",
    "src/core/tsi/ssl_transport_security.c",
    "src/core/tsi/transport_security.c",
    "src/core/census/grpc_context.c",
    "src/core/census/grpc_filter.c",
    "src/core/channel/channel_args.c",
    "src/core/channel/channel_stack.c",
    "src/core/channel/client_channel.c",
    "src/core/channel/client_uchannel.c",
    "src/core/channel/compress_filter.c",
    "src/core/channel/connected_channel.c",
    "src/core/channel/http_client_filter.c",
    "src/core/channel/http_server_filter.c",
    "src/core/channel/noop_filter.c",
    "src/core/client_config/client_config.c",
    "src/core/client_config/connector.c",
    "src/core/client_config/lb_policies/load_balancer_api.c",
    "src/core/client_config/lb_policies/pick_first.c",
    "src/core/client_config/lb_policies/round_robin.c",
    "src/core/client_config/lb_policy.c",
    "src/core/client_config/lb_policy_factory.c",
    "src/core/client_config/lb_policy_registry.c",
    "src/core/client_config/resolver.c",
    "src/core/client_config/resolver_factory.c",
    "src/core/client_config/resolver_registry.c",
    "src/core/client_config/resolvers/dns_resolver.c",
    "src/core/client_config/resolvers/sockaddr_resolver.c",
    "src/core/client_config/subchannel.c",
    "src/core/client_config/subchannel_factory.c",
    "src/core/client_config/subchannel_factory_decorators/add_channel_arg.c",
    "src/core/client_config/subchannel_factory_decorators/merge_channel_args.c",
    "src/core/client_config/uri_parser.c",
    "src/core/compression/algorithm.c",
    "src/core/compression/message_compress.c",
    "src/core/debug/trace.c",
    "src/core/httpcli/format_request.c",
    "src/core/httpcli/httpcli.c",
    "src/core/httpcli/parser.c",
    "src/core/iomgr/closure.c",
    "src/core/iomgr/endpoint.c",
    "src/core/iomgr/endpoint_pair_posix.c",
    "src/core/iomgr/endpoint_pair_windows.c",
    "src/core/iomgr/exec_ctx.c",
    "src/core/iomgr/executor.c",
    "src/core/iomgr/fd_posix.c",
    "src/core/iomgr/iocp_windows.c",
    "src/core/iomgr/iomgr.c",
    "src/core/iomgr/iomgr_posix.c",
    "src/core/iomgr/iomgr_windows.c",
    "src/core/iomgr/pollset_multipoller_with_epoll.c",
    "src/core/iomgr/pollset_multipoller_with_poll_posix.c",
    "src/core/iomgr/pollset_posix.c",
    "src/core/iomgr/pollset_set_posix.c",
    "src/core/iomgr/pollset_set_windows.c",
    "src/core/iomgr/pollset_windows.c",
    "src/core/iomgr/resolve_address_posix.c",
    "src/core/iomgr/resolve_address_windows.c",
    "src/core/iomgr/sockaddr_utils.c",
    "src/core/iomgr/socket_utils_common_posix.c",
    "src/core/iomgr/socket_utils_linux.c",
    "src/core/iomgr/socket_utils_posix.c",
    "src/core/iomgr/socket_windows.c",
    "src/core/iomgr/tcp_client_posix.c",
    "src/core/iomgr/tcp_client_windows.c",
    "src/core/iomgr/tcp_posix.c",
    "src/core/iomgr/tcp_server_posix.c",
    "src/core/iomgr/tcp_server_windows.c",
    "src/core/iomgr/tcp_windows.c",
    "src/core/iomgr/time_averaged_stats.c",
    "src/core/iomgr/timer.c",
    "src/core/iomgr/timer_heap.c",
    "src/core/iomgr/udp_server.c",
    "src/core/iomgr/wakeup_fd_eventfd.c",
    "src/core/iomgr/wakeup_fd_nospecial.c",
    "src/core/iomgr/wakeup_fd_pipe.c",
    "src/core/iomgr/wakeup_fd_posix.c",
    "src/core/iomgr/workqueue_posix.c",
    "src/core/iomgr/workqueue_windows.c",
    "src/core/json/json.c",
    "src/core/json/json_reader.c",
    "src/core/json/json_string.c",
    "src/core/json/json_writer.c",
    "src/core/proto/load_balancer.pb.c",
    "src/core/surface/api_trace.c",
    "src/core/surface/byte_buffer.c",
    "src/core/surface/byte_buffer_queue.c",
    "src/core/surface/byte_buffer_reader.c",
    "src/core/surface/call.c",
    "src/core/surface/call_details.c",
    "src/core/surface/call_log_batch.c",
    "src/core/surface/channel.c",
    "src/core/surface/channel_connectivity.c",
    "src/core/surface/channel_create.c",
    "src/core/surface/completion_queue.c",
    "src/core/surface/event_string.c",
    "src/core/surface/init.c",
    "src/core/surface/lame_client.c",
    "src/core/surface/metadata_array.c",
    "src/core/surface/server.c",
    "src/core/surface/server_chttp2.c",
    "src/core/surface/server_create.c",
    "src/core/surface/version.c",
    "src/core/transport/chttp2/alpn.c",
    "src/core/transport/chttp2/bin_encoder.c",
    "src/core/transport/chttp2/frame_data.c",
    "src/core/transport/chttp2/frame_goaway.c",
    "src/core/transport/chttp2/frame_ping.c",
    "src/core/transport/chttp2/frame_rst_stream.c",
    "src/core/transport/chttp2/frame_settings.c",
    "src/core/transport/chttp2/frame_window_update.c",
    "src/core/transport/chttp2/hpack_parser.c",
    "src/core/transport/chttp2/hpack_table.c",
    "src/core/transport/chttp2/huffsyms.c",
    "src/core/transport/chttp2/incoming_metadata.c",
    "src/core/transport/chttp2/parsing.c",
    "src/core/transport/chttp2/status_conversion.c",
    "src/core/transport/chttp2/stream_encoder.c",
    "src/core/transport/chttp2/stream_lists.c",
    "src/core/transport/chttp2/stream_map.c",
    "src/core/transport/chttp2/timeout_encoding.c",
    "src/core/transport/chttp2/varint.c",
    "src/core/transport/chttp2/writing.c",
    "src/core/transport/chttp2_transport.c",
    "src/core/transport/connectivity_state.c",
    "src/core/transport/metadata.c",
    "src/core/transport/stream_op.c",
    "src/core/transport/transport.c",
    "src/core/transport/transport_op_string.c",
    "third_party/nanopb/pb_common.c",
    "third_party/nanopb/pb_decode.c",
    "third_party/nanopb/pb_encode.c",
    "src/core/census/context.c",
    "src/core/census/initialize.c",
    "src/core/census/operation.c",
    "src/core/census/tracing.c",
  ],
  hdrs = [
    "include/grpc/grpc_security.h",
    "include/grpc/byte_buffer.h",
    "include/grpc/byte_buffer_reader.h",
    "include/grpc/compression.h",
    "include/grpc/grpc.h",
    "include/grpc/status.h",
    "include/grpc/census.h",
  ],
  includes = [
    "include",
    ".",
  ],
  deps = [
    "//external:libssl",
    "//external:zlib",
    ":gpr",
  ],
)


cc_library(
  name = "grpc_unsecure",
  srcs = [
    "src/core/census/grpc_filter.h",
    "src/core/channel/channel_args.h",
    "src/core/channel/channel_stack.h",
    "src/core/channel/client_channel.h",
    "src/core/channel/client_uchannel.h",
    "src/core/channel/compress_filter.h",
    "src/core/channel/connected_channel.h",
    "src/core/channel/context.h",
    "src/core/channel/http_client_filter.h",
    "src/core/channel/http_server_filter.h",
    "src/core/channel/noop_filter.h",
    "src/core/client_config/client_config.h",
    "src/core/client_config/connector.h",
    "src/core/client_config/lb_policies/load_balancer_api.h",
    "src/core/client_config/lb_policies/pick_first.h",
    "src/core/client_config/lb_policies/round_robin.h",
    "src/core/client_config/lb_policy.h",
    "src/core/client_config/lb_policy_factory.h",
    "src/core/client_config/lb_policy_registry.h",
    "src/core/client_config/resolver.h",
    "src/core/client_config/resolver_factory.h",
    "src/core/client_config/resolver_registry.h",
    "src/core/client_config/resolvers/dns_resolver.h",
    "src/core/client_config/resolvers/sockaddr_resolver.h",
    "src/core/client_config/subchannel.h",
    "src/core/client_config/subchannel_factory.h",
    "src/core/client_config/subchannel_factory_decorators/add_channel_arg.h",
    "src/core/client_config/subchannel_factory_decorators/merge_channel_args.h",
    "src/core/client_config/uri_parser.h",
    "src/core/compression/message_compress.h",
    "src/core/debug/trace.h",
    "src/core/httpcli/format_request.h",
    "src/core/httpcli/httpcli.h",
    "src/core/httpcli/parser.h",
    "src/core/iomgr/closure.h",
    "src/core/iomgr/endpoint.h",
    "src/core/iomgr/endpoint_pair.h",
    "src/core/iomgr/exec_ctx.h",
    "src/core/iomgr/executor.h",
    "src/core/iomgr/fd_posix.h",
    "src/core/iomgr/iocp_windows.h",
    "src/core/iomgr/iomgr.h",
    "src/core/iomgr/iomgr_internal.h",
    "src/core/iomgr/iomgr_posix.h",
    "src/core/iomgr/pollset.h",
    "src/core/iomgr/pollset_posix.h",
    "src/core/iomgr/pollset_set.h",
    "src/core/iomgr/pollset_set_posix.h",
    "src/core/iomgr/pollset_set_windows.h",
    "src/core/iomgr/pollset_windows.h",
    "src/core/iomgr/resolve_address.h",
    "src/core/iomgr/sockaddr.h",
    "src/core/iomgr/sockaddr_posix.h",
    "src/core/iomgr/sockaddr_utils.h",
    "src/core/iomgr/sockaddr_win32.h",
    "src/core/iomgr/socket_utils_posix.h",
    "src/core/iomgr/socket_windows.h",
    "src/core/iomgr/tcp_client.h",
    "src/core/iomgr/tcp_posix.h",
    "src/core/iomgr/tcp_server.h",
    "src/core/iomgr/tcp_windows.h",
    "src/core/iomgr/time_averaged_stats.h",
    "src/core/iomgr/timer.h",
    "src/core/iomgr/timer_heap.h",
    "src/core/iomgr/timer_internal.h",
    "src/core/iomgr/udp_server.h",
    "src/core/iomgr/wakeup_fd_pipe.h",
    "src/core/iomgr/wakeup_fd_posix.h",
    "src/core/iomgr/workqueue.h",
    "src/core/iomgr/workqueue_posix.h",
    "src/core/iomgr/workqueue_windows.h",
    "src/core/json/json.h",
    "src/core/json/json_common.h",
    "src/core/json/json_reader.h",
    "src/core/json/json_writer.h",
    "src/core/proto/load_balancer.pb.h",
    "src/core/statistics/census_interface.h",
    "src/core/statistics/census_rpc_stats.h",
    "src/core/surface/api_trace.h",
    "src/core/surface/byte_buffer_queue.h",
    "src/core/surface/call.h",
    "src/core/surface/call_test_only.h",
    "src/core/surface/channel.h",
    "src/core/surface/completion_queue.h",
    "src/core/surface/event_string.h",
    "src/core/surface/init.h",
    "src/core/surface/server.h",
    "src/core/surface/surface_trace.h",
    "src/core/transport/chttp2/alpn.h",
    "src/core/transport/chttp2/bin_encoder.h",
    "src/core/transport/chttp2/frame.h",
    "src/core/transport/chttp2/frame_data.h",
    "src/core/transport/chttp2/frame_goaway.h",
    "src/core/transport/chttp2/frame_ping.h",
    "src/core/transport/chttp2/frame_rst_stream.h",
    "src/core/transport/chttp2/frame_settings.h",
    "src/core/transport/chttp2/frame_window_update.h",
    "src/core/transport/chttp2/hpack_parser.h",
    "src/core/transport/chttp2/hpack_table.h",
    "src/core/transport/chttp2/http2_errors.h",
    "src/core/transport/chttp2/huffsyms.h",
    "src/core/transport/chttp2/incoming_metadata.h",
    "src/core/transport/chttp2/internal.h",
    "src/core/transport/chttp2/status_conversion.h",
    "src/core/transport/chttp2/stream_encoder.h",
    "src/core/transport/chttp2/stream_map.h",
    "src/core/transport/chttp2/timeout_encoding.h",
    "src/core/transport/chttp2/varint.h",
    "src/core/transport/chttp2_transport.h",
    "src/core/transport/connectivity_state.h",
    "src/core/transport/metadata.h",
    "src/core/transport/stream_op.h",
    "src/core/transport/transport.h",
    "src/core/transport/transport_impl.h",
    "third_party/nanopb/pb.h",
    "third_party/nanopb/pb_common.h",
    "third_party/nanopb/pb_decode.h",
    "third_party/nanopb/pb_encode.h",
    "src/core/census/aggregation.h",
    "src/core/census/context.h",
    "src/core/census/rpc_metric_id.h",
    "src/core/surface/init_unsecure.c",
    "src/core/census/grpc_context.c",
    "src/core/census/grpc_filter.c",
    "src/core/channel/channel_args.c",
    "src/core/channel/channel_stack.c",
    "src/core/channel/client_channel.c",
    "src/core/channel/client_uchannel.c",
    "src/core/channel/compress_filter.c",
    "src/core/channel/connected_channel.c",
    "src/core/channel/http_client_filter.c",
    "src/core/channel/http_server_filter.c",
    "src/core/channel/noop_filter.c",
    "src/core/client_config/client_config.c",
    "src/core/client_config/connector.c",
    "src/core/client_config/lb_policies/load_balancer_api.c",
    "src/core/client_config/lb_policies/pick_first.c",
    "src/core/client_config/lb_policies/round_robin.c",
    "src/core/client_config/lb_policy.c",
    "src/core/client_config/lb_policy_factory.c",
    "src/core/client_config/lb_policy_registry.c",
    "src/core/client_config/resolver.c",
    "src/core/client_config/resolver_factory.c",
    "src/core/client_config/resolver_registry.c",
    "src/core/client_config/resolvers/dns_resolver.c",
    "src/core/client_config/resolvers/sockaddr_resolver.c",
    "src/core/client_config/subchannel.c",
    "src/core/client_config/subchannel_factory.c",
    "src/core/client_config/subchannel_factory_decorators/add_channel_arg.c",
    "src/core/client_config/subchannel_factory_decorators/merge_channel_args.c",
    "src/core/client_config/uri_parser.c",
    "src/core/compression/algorithm.c",
    "src/core/compression/message_compress.c",
    "src/core/debug/trace.c",
    "src/core/httpcli/format_request.c",
    "src/core/httpcli/httpcli.c",
    "src/core/httpcli/parser.c",
    "src/core/iomgr/closure.c",
    "src/core/iomgr/endpoint.c",
    "src/core/iomgr/endpoint_pair_posix.c",
    "src/core/iomgr/endpoint_pair_windows.c",
    "src/core/iomgr/exec_ctx.c",
    "src/core/iomgr/executor.c",
    "src/core/iomgr/fd_posix.c",
    "src/core/iomgr/iocp_windows.c",
    "src/core/iomgr/iomgr.c",
    "src/core/iomgr/iomgr_posix.c",
    "src/core/iomgr/iomgr_windows.c",
    "src/core/iomgr/pollset_multipoller_with_epoll.c",
    "src/core/iomgr/pollset_multipoller_with_poll_posix.c",
    "src/core/iomgr/pollset_posix.c",
    "src/core/iomgr/pollset_set_posix.c",
    "src/core/iomgr/pollset_set_windows.c",
    "src/core/iomgr/pollset_windows.c",
    "src/core/iomgr/resolve_address_posix.c",
    "src/core/iomgr/resolve_address_windows.c",
    "src/core/iomgr/sockaddr_utils.c",
    "src/core/iomgr/socket_utils_common_posix.c",
    "src/core/iomgr/socket_utils_linux.c",
    "src/core/iomgr/socket_utils_posix.c",
    "src/core/iomgr/socket_windows.c",
    "src/core/iomgr/tcp_client_posix.c",
    "src/core/iomgr/tcp_client_windows.c",
    "src/core/iomgr/tcp_posix.c",
    "src/core/iomgr/tcp_server_posix.c",
    "src/core/iomgr/tcp_server_windows.c",
    "src/core/iomgr/tcp_windows.c",
    "src/core/iomgr/time_averaged_stats.c",
    "src/core/iomgr/timer.c",
    "src/core/iomgr/timer_heap.c",
    "src/core/iomgr/udp_server.c",
    "src/core/iomgr/wakeup_fd_eventfd.c",
    "src/core/iomgr/wakeup_fd_nospecial.c",
    "src/core/iomgr/wakeup_fd_pipe.c",
    "src/core/iomgr/wakeup_fd_posix.c",
    "src/core/iomgr/workqueue_posix.c",
    "src/core/iomgr/workqueue_windows.c",
    "src/core/json/json.c",
    "src/core/json/json_reader.c",
    "src/core/json/json_string.c",
    "src/core/json/json_writer.c",
    "src/core/proto/load_balancer.pb.c",
    "src/core/surface/api_trace.c",
    "src/core/surface/byte_buffer.c",
    "src/core/surface/byte_buffer_queue.c",
    "src/core/surface/byte_buffer_reader.c",
    "src/core/surface/call.c",
    "src/core/surface/call_details.c",
    "src/core/surface/call_log_batch.c",
    "src/core/surface/channel.c",
    "src/core/surface/channel_connectivity.c",
    "src/core/surface/channel_create.c",
    "src/core/surface/completion_queue.c",
    "src/core/surface/event_string.c",
    "src/core/surface/init.c",
    "src/core/surface/lame_client.c",
    "src/core/surface/metadata_array.c",
    "src/core/surface/server.c",
    "src/core/surface/server_chttp2.c",
    "src/core/surface/server_create.c",
    "src/core/surface/version.c",
    "src/core/transport/chttp2/alpn.c",
    "src/core/transport/chttp2/bin_encoder.c",
    "src/core/transport/chttp2/frame_data.c",
    "src/core/transport/chttp2/frame_goaway.c",
    "src/core/transport/chttp2/frame_ping.c",
    "src/core/transport/chttp2/frame_rst_stream.c",
    "src/core/transport/chttp2/frame_settings.c",
    "src/core/transport/chttp2/frame_window_update.c",
    "src/core/transport/chttp2/hpack_parser.c",
    "src/core/transport/chttp2/hpack_table.c",
    "src/core/transport/chttp2/huffsyms.c",
    "src/core/transport/chttp2/incoming_metadata.c",
    "src/core/transport/chttp2/parsing.c",
    "src/core/transport/chttp2/status_conversion.c",
    "src/core/transport/chttp2/stream_encoder.c",
    "src/core/transport/chttp2/stream_lists.c",
    "src/core/transport/chttp2/stream_map.c",
    "src/core/transport/chttp2/timeout_encoding.c",
    "src/core/transport/chttp2/varint.c",
    "src/core/transport/chttp2/writing.c",
    "src/core/transport/chttp2_transport.c",
    "src/core/transport/connectivity_state.c",
    "src/core/transport/metadata.c",
    "src/core/transport/stream_op.c",
    "src/core/transport/transport.c",
    "src/core/transport/transport_op_string.c",
    "third_party/nanopb/pb_common.c",
    "third_party/nanopb/pb_decode.c",
    "third_party/nanopb/pb_encode.c",
    "src/core/census/context.c",
    "src/core/census/initialize.c",
    "src/core/census/operation.c",
    "src/core/census/tracing.c",
  ],
  hdrs = [
    "include/grpc/byte_buffer.h",
    "include/grpc/byte_buffer_reader.h",
    "include/grpc/compression.h",
    "include/grpc/grpc.h",
    "include/grpc/status.h",
    "include/grpc/census.h",
  ],
  includes = [
    "include",
    ".",
  ],
  deps = [
    ":gpr",
  ],
)


cc_library(
  name = "grpc_zookeeper",
  srcs = [
    "src/core/client_config/resolvers/zookeeper_resolver.h",
    "src/core/client_config/resolvers/zookeeper_resolver.c",
  ],
  hdrs = [
    "include/grpc/grpc_zookeeper.h",
  ],
  includes = [
    "include",
    ".",
  ],
  deps = [
    ":gpr",
    ":grpc",
  ],
)


cc_library(
  name = "grpc++",
  srcs = [
    "src/cpp/client/secure_credentials.h",
    "src/cpp/common/secure_auth_context.h",
    "src/cpp/server/secure_server_credentials.h",
    "src/cpp/client/create_channel_internal.h",
    "src/cpp/common/create_auth_context.h",
    "src/cpp/server/dynamic_thread_pool.h",
    "src/cpp/server/fixed_size_thread_pool.h",
    "src/cpp/server/thread_pool_interface.h",
    "src/cpp/client/secure_channel_arguments.cc",
    "src/cpp/client/secure_credentials.cc",
    "src/cpp/common/auth_property_iterator.cc",
    "src/cpp/common/secure_auth_context.cc",
    "src/cpp/common/secure_create_auth_context.cc",
    "src/cpp/server/secure_server_credentials.cc",
    "src/cpp/client/channel.cc",
    "src/cpp/client/channel_arguments.cc",
    "src/cpp/client/client_context.cc",
    "src/cpp/client/create_channel.cc",
    "src/cpp/client/create_channel_internal.cc",
    "src/cpp/client/credentials.cc",
    "src/cpp/client/generic_stub.cc",
    "src/cpp/client/insecure_credentials.cc",
    "src/cpp/common/call.cc",
    "src/cpp/common/completion_queue.cc",
    "src/cpp/common/rpc_method.cc",
    "src/cpp/proto/proto_utils.cc",
    "src/cpp/server/async_generic_service.cc",
    "src/cpp/server/create_default_thread_pool.cc",
    "src/cpp/server/dynamic_thread_pool.cc",
    "src/cpp/server/fixed_size_thread_pool.cc",
    "src/cpp/server/insecure_server_credentials.cc",
    "src/cpp/server/server.cc",
    "src/cpp/server/server_builder.cc",
    "src/cpp/server/server_context.cc",
    "src/cpp/server/server_credentials.cc",
    "src/cpp/util/byte_buffer.cc",
    "src/cpp/util/slice.cc",
    "src/cpp/util/status.cc",
    "src/cpp/util/string_ref.cc",
    "src/cpp/util/time.cc",
  ],
  hdrs = [
    "include/grpc++/channel.h",
    "include/grpc++/client_context.h",
    "include/grpc++/completion_queue.h",
    "include/grpc++/create_channel.h",
    "include/grpc++/generic/async_generic_service.h",
    "include/grpc++/generic/generic_stub.h",
    "include/grpc++/grpc++.h",
    "include/grpc++/impl/call.h",
    "include/grpc++/impl/client_unary_call.h",
    "include/grpc++/impl/grpc_library.h",
    "include/grpc++/impl/proto_utils.h",
    "include/grpc++/impl/rpc_method.h",
    "include/grpc++/impl/rpc_service_method.h",
    "include/grpc++/impl/serialization_traits.h",
    "include/grpc++/impl/service_type.h",
    "include/grpc++/impl/sync.h",
    "include/grpc++/impl/sync_cxx11.h",
    "include/grpc++/impl/sync_no_cxx11.h",
    "include/grpc++/impl/thd.h",
    "include/grpc++/impl/thd_cxx11.h",
    "include/grpc++/impl/thd_no_cxx11.h",
    "include/grpc++/security/auth_context.h",
    "include/grpc++/security/auth_metadata_processor.h",
    "include/grpc++/security/credentials.h",
    "include/grpc++/security/server_credentials.h",
    "include/grpc++/server.h",
    "include/grpc++/server_builder.h",
    "include/grpc++/server_context.h",
    "include/grpc++/support/async_stream.h",
    "include/grpc++/support/async_unary_call.h",
    "include/grpc++/support/byte_buffer.h",
    "include/grpc++/support/channel_arguments.h",
    "include/grpc++/support/config.h",
    "include/grpc++/support/config_protobuf.h",
    "include/grpc++/support/slice.h",
    "include/grpc++/support/status.h",
    "include/grpc++/support/status_code_enum.h",
    "include/grpc++/support/string_ref.h",
    "include/grpc++/support/stub_options.h",
    "include/grpc++/support/sync_stream.h",
    "include/grpc++/support/time.h",
  ],
  includes = [
    "include",
    ".",
  ],
  deps = [
    "//external:libssl",
    "//external:protobuf_clib",
    ":gpr",
    ":grpc",
  ],
)


cc_library(
  name = "grpc++_unsecure",
  srcs = [
    "src/cpp/client/create_channel_internal.h",
    "src/cpp/common/create_auth_context.h",
    "src/cpp/server/dynamic_thread_pool.h",
    "src/cpp/server/fixed_size_thread_pool.h",
    "src/cpp/server/thread_pool_interface.h",
    "src/cpp/common/insecure_create_auth_context.cc",
    "src/cpp/client/channel.cc",
    "src/cpp/client/channel_arguments.cc",
    "src/cpp/client/client_context.cc",
    "src/cpp/client/create_channel.cc",
    "src/cpp/client/create_channel_internal.cc",
    "src/cpp/client/credentials.cc",
    "src/cpp/client/generic_stub.cc",
    "src/cpp/client/insecure_credentials.cc",
    "src/cpp/common/call.cc",
    "src/cpp/common/completion_queue.cc",
    "src/cpp/common/rpc_method.cc",
    "src/cpp/proto/proto_utils.cc",
    "src/cpp/server/async_generic_service.cc",
    "src/cpp/server/create_default_thread_pool.cc",
    "src/cpp/server/dynamic_thread_pool.cc",
    "src/cpp/server/fixed_size_thread_pool.cc",
    "src/cpp/server/insecure_server_credentials.cc",
    "src/cpp/server/server.cc",
    "src/cpp/server/server_builder.cc",
    "src/cpp/server/server_context.cc",
    "src/cpp/server/server_credentials.cc",
    "src/cpp/util/byte_buffer.cc",
    "src/cpp/util/slice.cc",
    "src/cpp/util/status.cc",
    "src/cpp/util/string_ref.cc",
    "src/cpp/util/time.cc",
  ],
  hdrs = [
    "include/grpc++/channel.h",
    "include/grpc++/client_context.h",
    "include/grpc++/completion_queue.h",
    "include/grpc++/create_channel.h",
    "include/grpc++/generic/async_generic_service.h",
    "include/grpc++/generic/generic_stub.h",
    "include/grpc++/grpc++.h",
    "include/grpc++/impl/call.h",
    "include/grpc++/impl/client_unary_call.h",
    "include/grpc++/impl/grpc_library.h",
    "include/grpc++/impl/proto_utils.h",
    "include/grpc++/impl/rpc_method.h",
    "include/grpc++/impl/rpc_service_method.h",
    "include/grpc++/impl/serialization_traits.h",
    "include/grpc++/impl/service_type.h",
    "include/grpc++/impl/sync.h",
    "include/grpc++/impl/sync_cxx11.h",
    "include/grpc++/impl/sync_no_cxx11.h",
    "include/grpc++/impl/thd.h",
    "include/grpc++/impl/thd_cxx11.h",
    "include/grpc++/impl/thd_no_cxx11.h",
    "include/grpc++/security/auth_context.h",
    "include/grpc++/security/auth_metadata_processor.h",
    "include/grpc++/security/credentials.h",
    "include/grpc++/security/server_credentials.h",
    "include/grpc++/server.h",
    "include/grpc++/server_builder.h",
    "include/grpc++/server_context.h",
    "include/grpc++/support/async_stream.h",
    "include/grpc++/support/async_unary_call.h",
    "include/grpc++/support/byte_buffer.h",
    "include/grpc++/support/channel_arguments.h",
    "include/grpc++/support/config.h",
    "include/grpc++/support/config_protobuf.h",
    "include/grpc++/support/slice.h",
    "include/grpc++/support/status.h",
    "include/grpc++/support/status_code_enum.h",
    "include/grpc++/support/string_ref.h",
    "include/grpc++/support/stub_options.h",
    "include/grpc++/support/sync_stream.h",
    "include/grpc++/support/time.h",
  ],
  includes = [
    "include",
    ".",
  ],
  deps = [
    "//external:protobuf_clib",
    ":gpr",
    ":grpc_unsecure",
  ],
)


cc_library(
  name = "grpc_plugin_support",
  srcs = [
    "include/grpc++/support/config.h",
    "include/grpc++/support/config_protobuf.h",
    "src/compiler/config.h",
    "src/compiler/cpp_generator.h",
    "src/compiler/cpp_generator_helpers.h",
    "src/compiler/csharp_generator.h",
    "src/compiler/csharp_generator_helpers.h",
    "src/compiler/generator_helpers.h",
    "src/compiler/objective_c_generator.h",
    "src/compiler/objective_c_generator_helpers.h",
    "src/compiler/python_generator.h",
    "src/compiler/ruby_generator.h",
    "src/compiler/ruby_generator_helpers-inl.h",
    "src/compiler/ruby_generator_map-inl.h",
    "src/compiler/ruby_generator_string-inl.h",
    "src/compiler/cpp_generator.cc",
    "src/compiler/csharp_generator.cc",
    "src/compiler/objective_c_generator.cc",
    "src/compiler/python_generator.cc",
    "src/compiler/ruby_generator.cc",
  ],
  hdrs = [
  ],
  includes = [
    "include",
    ".",
  ],
  deps = [
    "//external:protobuf_compiler",
  ],
)


cc_library(
  name = "grpc_csharp_ext",
  srcs = [
    "src/csharp/ext/grpc_csharp_ext.c",
  ],
  hdrs = [
  ],
  includes = [
    "include",
    ".",
  ],
  deps = [
    ":gpr",
    ":grpc",
  ],
)



objc_library(
  name = "gpr_objc",
  srcs = [
    "src/core/profiling/basic_timers.c",
    "src/core/profiling/stap_timers.c",
    "src/core/support/alloc.c",
    "src/core/support/cmdline.c",
    "src/core/support/cpu_iphone.c",
    "src/core/support/cpu_linux.c",
    "src/core/support/cpu_posix.c",
    "src/core/support/cpu_windows.c",
    "src/core/support/env_linux.c",
    "src/core/support/env_posix.c",
    "src/core/support/env_win32.c",
    "src/core/support/file.c",
    "src/core/support/file_posix.c",
    "src/core/support/file_win32.c",
    "src/core/support/histogram.c",
    "src/core/support/host_port.c",
    "src/core/support/log.c",
    "src/core/support/log_android.c",
    "src/core/support/log_linux.c",
    "src/core/support/log_posix.c",
    "src/core/support/log_win32.c",
    "src/core/support/murmur_hash.c",
    "src/core/support/slice.c",
    "src/core/support/slice_buffer.c",
    "src/core/support/stack_lockfree.c",
    "src/core/support/string.c",
    "src/core/support/string_posix.c",
    "src/core/support/string_win32.c",
    "src/core/support/subprocess_posix.c",
    "src/core/support/sync.c",
    "src/core/support/sync_posix.c",
    "src/core/support/sync_win32.c",
    "src/core/support/thd.c",
    "src/core/support/thd_posix.c",
    "src/core/support/thd_win32.c",
    "src/core/support/time.c",
    "src/core/support/time_posix.c",
    "src/core/support/time_precise.c",
    "src/core/support/time_win32.c",
    "src/core/support/tls_pthread.c",
  ],
  hdrs = [
    "include/grpc/support/alloc.h",
    "include/grpc/support/atm.h",
    "include/grpc/support/atm_gcc_atomic.h",
    "include/grpc/support/atm_gcc_sync.h",
    "include/grpc/support/atm_win32.h",
    "include/grpc/support/cmdline.h",
    "include/grpc/support/cpu.h",
    "include/grpc/support/histogram.h",
    "include/grpc/support/host_port.h",
    "include/grpc/support/log.h",
    "include/grpc/support/log_win32.h",
    "include/grpc/support/port_platform.h",
    "include/grpc/support/slice.h",
    "include/grpc/support/slice_buffer.h",
    "include/grpc/support/string_util.h",
    "include/grpc/support/subprocess.h",
    "include/grpc/support/sync.h",
    "include/grpc/support/sync_generic.h",
    "include/grpc/support/sync_posix.h",
    "include/grpc/support/sync_win32.h",
    "include/grpc/support/thd.h",
    "include/grpc/support/time.h",
    "include/grpc/support/tls.h",
    "include/grpc/support/tls_gcc.h",
    "include/grpc/support/tls_msvc.h",
    "include/grpc/support/tls_pthread.h",
    "include/grpc/support/useful.h",
    "src/core/profiling/timers.h",
    "src/core/support/block_annotate.h",
    "src/core/support/env.h",
    "src/core/support/file.h",
    "src/core/support/murmur_hash.h",
    "src/core/support/stack_lockfree.h",
    "src/core/support/string.h",
    "src/core/support/string_win32.h",
    "src/core/support/thd_internal.h",
    "src/core/support/time_precise.h",
  ],
  includes = [
    "include",
    ".",
  ],
  deps = [
  ],
)


objc_library(
  name = "grpc_objc",
  srcs = [
    "src/core/httpcli/httpcli_security_connector.c",
    "src/core/security/base64.c",
    "src/core/security/client_auth_filter.c",
    "src/core/security/credentials.c",
    "src/core/security/credentials_metadata.c",
    "src/core/security/credentials_posix.c",
    "src/core/security/credentials_win32.c",
    "src/core/security/google_default_credentials.c",
    "src/core/security/handshake.c",
    "src/core/security/json_token.c",
    "src/core/security/jwt_verifier.c",
    "src/core/security/secure_endpoint.c",
    "src/core/security/security_connector.c",
    "src/core/security/security_context.c",
    "src/core/security/server_auth_filter.c",
    "src/core/security/server_secure_chttp2.c",
    "src/core/surface/init_secure.c",
    "src/core/surface/secure_channel_create.c",
    "src/core/tsi/fake_transport_security.c",
    "src/core/tsi/ssl_transport_security.c",
    "src/core/tsi/transport_security.c",
    "src/core/census/grpc_context.c",
    "src/core/census/grpc_filter.c",
    "src/core/channel/channel_args.c",
    "src/core/channel/channel_stack.c",
    "src/core/channel/client_channel.c",
    "src/core/channel/client_uchannel.c",
    "src/core/channel/compress_filter.c",
    "src/core/channel/connected_channel.c",
    "src/core/channel/http_client_filter.c",
    "src/core/channel/http_server_filter.c",
    "src/core/channel/noop_filter.c",
    "src/core/client_config/client_config.c",
    "src/core/client_config/connector.c",
    "src/core/client_config/lb_policies/load_balancer_api.c",
    "src/core/client_config/lb_policies/pick_first.c",
    "src/core/client_config/lb_policies/round_robin.c",
    "src/core/client_config/lb_policy.c",
    "src/core/client_config/lb_policy_factory.c",
    "src/core/client_config/lb_policy_registry.c",
    "src/core/client_config/resolver.c",
    "src/core/client_config/resolver_factory.c",
    "src/core/client_config/resolver_registry.c",
    "src/core/client_config/resolvers/dns_resolver.c",
    "src/core/client_config/resolvers/sockaddr_resolver.c",
    "src/core/client_config/subchannel.c",
    "src/core/client_config/subchannel_factory.c",
    "src/core/client_config/subchannel_factory_decorators/add_channel_arg.c",
    "src/core/client_config/subchannel_factory_decorators/merge_channel_args.c",
    "src/core/client_config/uri_parser.c",
    "src/core/compression/algorithm.c",
    "src/core/compression/message_compress.c",
    "src/core/debug/trace.c",
    "src/core/httpcli/format_request.c",
    "src/core/httpcli/httpcli.c",
    "src/core/httpcli/parser.c",
    "src/core/iomgr/closure.c",
    "src/core/iomgr/endpoint.c",
    "src/core/iomgr/endpoint_pair_posix.c",
    "src/core/iomgr/endpoint_pair_windows.c",
    "src/core/iomgr/exec_ctx.c",
    "src/core/iomgr/executor.c",
    "src/core/iomgr/fd_posix.c",
    "src/core/iomgr/iocp_windows.c",
    "src/core/iomgr/iomgr.c",
    "src/core/iomgr/iomgr_posix.c",
    "src/core/iomgr/iomgr_windows.c",
    "src/core/iomgr/pollset_multipoller_with_epoll.c",
    "src/core/iomgr/pollset_multipoller_with_poll_posix.c",
    "src/core/iomgr/pollset_posix.c",
    "src/core/iomgr/pollset_set_posix.c",
    "src/core/iomgr/pollset_set_windows.c",
    "src/core/iomgr/pollset_windows.c",
    "src/core/iomgr/resolve_address_posix.c",
    "src/core/iomgr/resolve_address_windows.c",
    "src/core/iomgr/sockaddr_utils.c",
    "src/core/iomgr/socket_utils_common_posix.c",
    "src/core/iomgr/socket_utils_linux.c",
    "src/core/iomgr/socket_utils_posix.c",
    "src/core/iomgr/socket_windows.c",
    "src/core/iomgr/tcp_client_posix.c",
    "src/core/iomgr/tcp_client_windows.c",
    "src/core/iomgr/tcp_posix.c",
    "src/core/iomgr/tcp_server_posix.c",
    "src/core/iomgr/tcp_server_windows.c",
    "src/core/iomgr/tcp_windows.c",
    "src/core/iomgr/time_averaged_stats.c",
    "src/core/iomgr/timer.c",
    "src/core/iomgr/timer_heap.c",
    "src/core/iomgr/udp_server.c",
    "src/core/iomgr/wakeup_fd_eventfd.c",
    "src/core/iomgr/wakeup_fd_nospecial.c",
    "src/core/iomgr/wakeup_fd_pipe.c",
    "src/core/iomgr/wakeup_fd_posix.c",
    "src/core/iomgr/workqueue_posix.c",
    "src/core/iomgr/workqueue_windows.c",
    "src/core/json/json.c",
    "src/core/json/json_reader.c",
    "src/core/json/json_string.c",
    "src/core/json/json_writer.c",
    "src/core/proto/load_balancer.pb.c",
    "src/core/surface/api_trace.c",
    "src/core/surface/byte_buffer.c",
    "src/core/surface/byte_buffer_queue.c",
    "src/core/surface/byte_buffer_reader.c",
    "src/core/surface/call.c",
    "src/core/surface/call_details.c",
    "src/core/surface/call_log_batch.c",
    "src/core/surface/channel.c",
    "src/core/surface/channel_connectivity.c",
    "src/core/surface/channel_create.c",
    "src/core/surface/completion_queue.c",
    "src/core/surface/event_string.c",
    "src/core/surface/init.c",
    "src/core/surface/lame_client.c",
    "src/core/surface/metadata_array.c",
    "src/core/surface/server.c",
    "src/core/surface/server_chttp2.c",
    "src/core/surface/server_create.c",
    "src/core/surface/version.c",
    "src/core/transport/chttp2/alpn.c",
    "src/core/transport/chttp2/bin_encoder.c",
    "src/core/transport/chttp2/frame_data.c",
    "src/core/transport/chttp2/frame_goaway.c",
    "src/core/transport/chttp2/frame_ping.c",
    "src/core/transport/chttp2/frame_rst_stream.c",
    "src/core/transport/chttp2/frame_settings.c",
    "src/core/transport/chttp2/frame_window_update.c",
    "src/core/transport/chttp2/hpack_parser.c",
    "src/core/transport/chttp2/hpack_table.c",
    "src/core/transport/chttp2/huffsyms.c",
    "src/core/transport/chttp2/incoming_metadata.c",
    "src/core/transport/chttp2/parsing.c",
    "src/core/transport/chttp2/status_conversion.c",
    "src/core/transport/chttp2/stream_encoder.c",
    "src/core/transport/chttp2/stream_lists.c",
    "src/core/transport/chttp2/stream_map.c",
    "src/core/transport/chttp2/timeout_encoding.c",
    "src/core/transport/chttp2/varint.c",
    "src/core/transport/chttp2/writing.c",
    "src/core/transport/chttp2_transport.c",
    "src/core/transport/connectivity_state.c",
    "src/core/transport/metadata.c",
    "src/core/transport/stream_op.c",
    "src/core/transport/transport.c",
    "src/core/transport/transport_op_string.c",
    "third_party/nanopb/pb_common.c",
    "third_party/nanopb/pb_decode.c",
    "third_party/nanopb/pb_encode.c",
    "src/core/census/context.c",
    "src/core/census/initialize.c",
    "src/core/census/operation.c",
    "src/core/census/tracing.c",
  ],
  hdrs = [
    "include/grpc/grpc_security.h",
    "include/grpc/byte_buffer.h",
    "include/grpc/byte_buffer_reader.h",
    "include/grpc/compression.h",
    "include/grpc/grpc.h",
    "include/grpc/status.h",
    "include/grpc/census.h",
    "src/core/security/auth_filters.h",
    "src/core/security/base64.h",
    "src/core/security/credentials.h",
    "src/core/security/handshake.h",
    "src/core/security/json_token.h",
    "src/core/security/jwt_verifier.h",
    "src/core/security/secure_endpoint.h",
    "src/core/security/security_connector.h",
    "src/core/security/security_context.h",
    "src/core/tsi/fake_transport_security.h",
    "src/core/tsi/ssl_transport_security.h",
    "src/core/tsi/transport_security.h",
    "src/core/tsi/transport_security_interface.h",
    "src/core/census/grpc_filter.h",
    "src/core/channel/channel_args.h",
    "src/core/channel/channel_stack.h",
    "src/core/channel/client_channel.h",
    "src/core/channel/client_uchannel.h",
    "src/core/channel/compress_filter.h",
    "src/core/channel/connected_channel.h",
    "src/core/channel/context.h",
    "src/core/channel/http_client_filter.h",
    "src/core/channel/http_server_filter.h",
    "src/core/channel/noop_filter.h",
    "src/core/client_config/client_config.h",
    "src/core/client_config/connector.h",
    "src/core/client_config/lb_policies/load_balancer_api.h",
    "src/core/client_config/lb_policies/pick_first.h",
    "src/core/client_config/lb_policies/round_robin.h",
    "src/core/client_config/lb_policy.h",
    "src/core/client_config/lb_policy_factory.h",
    "src/core/client_config/lb_policy_registry.h",
    "src/core/client_config/resolver.h",
    "src/core/client_config/resolver_factory.h",
    "src/core/client_config/resolver_registry.h",
    "src/core/client_config/resolvers/dns_resolver.h",
    "src/core/client_config/resolvers/sockaddr_resolver.h",
    "src/core/client_config/subchannel.h",
    "src/core/client_config/subchannel_factory.h",
    "src/core/client_config/subchannel_factory_decorators/add_channel_arg.h",
    "src/core/client_config/subchannel_factory_decorators/merge_channel_args.h",
    "src/core/client_config/uri_parser.h",
    "src/core/compression/message_compress.h",
    "src/core/debug/trace.h",
    "src/core/httpcli/format_request.h",
    "src/core/httpcli/httpcli.h",
    "src/core/httpcli/parser.h",
    "src/core/iomgr/closure.h",
    "src/core/iomgr/endpoint.h",
    "src/core/iomgr/endpoint_pair.h",
    "src/core/iomgr/exec_ctx.h",
    "src/core/iomgr/executor.h",
    "src/core/iomgr/fd_posix.h",
    "src/core/iomgr/iocp_windows.h",
    "src/core/iomgr/iomgr.h",
    "src/core/iomgr/iomgr_internal.h",
    "src/core/iomgr/iomgr_posix.h",
    "src/core/iomgr/pollset.h",
    "src/core/iomgr/pollset_posix.h",
    "src/core/iomgr/pollset_set.h",
    "src/core/iomgr/pollset_set_posix.h",
    "src/core/iomgr/pollset_set_windows.h",
    "src/core/iomgr/pollset_windows.h",
    "src/core/iomgr/resolve_address.h",
    "src/core/iomgr/sockaddr.h",
    "src/core/iomgr/sockaddr_posix.h",
    "src/core/iomgr/sockaddr_utils.h",
    "src/core/iomgr/sockaddr_win32.h",
    "src/core/iomgr/socket_utils_posix.h",
    "src/core/iomgr/socket_windows.h",
    "src/core/iomgr/tcp_client.h",
    "src/core/iomgr/tcp_posix.h",
    "src/core/iomgr/tcp_server.h",
    "src/core/iomgr/tcp_windows.h",
    "src/core/iomgr/time_averaged_stats.h",
    "src/core/iomgr/timer.h",
    "src/core/iomgr/timer_heap.h",
    "src/core/iomgr/timer_internal.h",
    "src/core/iomgr/udp_server.h",
    "src/core/iomgr/wakeup_fd_pipe.h",
    "src/core/iomgr/wakeup_fd_posix.h",
    "src/core/iomgr/workqueue.h",
    "src/core/iomgr/workqueue_posix.h",
    "src/core/iomgr/workqueue_windows.h",
    "src/core/json/json.h",
    "src/core/json/json_common.h",
    "src/core/json/json_reader.h",
    "src/core/json/json_writer.h",
    "src/core/proto/load_balancer.pb.h",
    "src/core/statistics/census_interface.h",
    "src/core/statistics/census_rpc_stats.h",
    "src/core/surface/api_trace.h",
    "src/core/surface/byte_buffer_queue.h",
    "src/core/surface/call.h",
    "src/core/surface/call_test_only.h",
    "src/core/surface/channel.h",
    "src/core/surface/completion_queue.h",
    "src/core/surface/event_string.h",
    "src/core/surface/init.h",
    "src/core/surface/server.h",
    "src/core/surface/surface_trace.h",
    "src/core/transport/chttp2/alpn.h",
    "src/core/transport/chttp2/bin_encoder.h",
    "src/core/transport/chttp2/frame.h",
    "src/core/transport/chttp2/frame_data.h",
    "src/core/transport/chttp2/frame_goaway.h",
    "src/core/transport/chttp2/frame_ping.h",
    "src/core/transport/chttp2/frame_rst_stream.h",
    "src/core/transport/chttp2/frame_settings.h",
    "src/core/transport/chttp2/frame_window_update.h",
    "src/core/transport/chttp2/hpack_parser.h",
    "src/core/transport/chttp2/hpack_table.h",
    "src/core/transport/chttp2/http2_errors.h",
    "src/core/transport/chttp2/huffsyms.h",
    "src/core/transport/chttp2/incoming_metadata.h",
    "src/core/transport/chttp2/internal.h",
    "src/core/transport/chttp2/status_conversion.h",
    "src/core/transport/chttp2/stream_encoder.h",
    "src/core/transport/chttp2/stream_map.h",
    "src/core/transport/chttp2/timeout_encoding.h",
    "src/core/transport/chttp2/varint.h",
    "src/core/transport/chttp2_transport.h",
    "src/core/transport/connectivity_state.h",
    "src/core/transport/metadata.h",
    "src/core/transport/stream_op.h",
    "src/core/transport/transport.h",
    "src/core/transport/transport_impl.h",
    "third_party/nanopb/pb.h",
    "third_party/nanopb/pb_common.h",
    "third_party/nanopb/pb_decode.h",
    "third_party/nanopb/pb_encode.h",
    "src/core/census/aggregation.h",
    "src/core/census/context.h",
    "src/core/census/rpc_metric_id.h",
  ],
  includes = [
    "include",
    ".",
  ],
  deps = [
    ":gpr_objc",
    "//external:libssl_objc",
  ],
  sdk_dylibs = ["libz"],
)



cc_binary(
  name = "grpc_cpp_plugin",
  srcs = [
    "src/compiler/cpp_plugin.cc",
  ],
  deps = [
    "//external:protobuf_compiler",
    ":grpc_plugin_support",
  ],
)


cc_binary(
  name = "grpc_csharp_plugin",
  srcs = [
    "src/compiler/csharp_plugin.cc",
  ],
  deps = [
    "//external:protobuf_compiler",
    ":grpc_plugin_support",
  ],
)


cc_binary(
  name = "grpc_objective_c_plugin",
  srcs = [
    "src/compiler/objective_c_plugin.cc",
  ],
  deps = [
    "//external:protobuf_compiler",
    ":grpc_plugin_support",
  ],
)


cc_binary(
  name = "grpc_python_plugin",
  srcs = [
    "src/compiler/python_plugin.cc",
  ],
  deps = [
    "//external:protobuf_compiler",
    ":grpc_plugin_support",
  ],
)


cc_binary(
  name = "grpc_ruby_plugin",
  srcs = [
    "src/compiler/ruby_plugin.cc",
  ],
  deps = [
    "//external:protobuf_compiler",
    ":grpc_plugin_support",
  ],
)








objc_path = "src/objective-c"

rx_library_path = objc_path + "/RxLibrary"

objc_library(
  name = "rx_library",
  hdrs = glob([
    rx_library_path + "/*.h",
    rx_library_path + "/transformations/*.h",
  ]),
  srcs = glob([
    rx_library_path + "/*.m",
    rx_library_path + "/transformations/*.m",
  ]),
  includes = [objc_path],
  deps = [
    ":rx_library_private",
  ],
)

objc_library(
  name = "rx_library_private",
  hdrs = glob([rx_library_path + "/private/*.h"]),
  srcs = glob([rx_library_path + "/private/*.m"]),
  visibility = ["//visibility:private"],
)

objc_client_path = objc_path + "/GRPCClient"

objc_library(
  name = "grpc_client",
  hdrs = glob([
    objc_client_path + "/*.h",
    objc_client_path + "/private/*.h",
  ]),
  srcs = glob([
    objc_client_path + "/*.m",
    objc_client_path + "/private/*.m",
  ]),
  includes = [objc_path],
  bundles = [":gRPCCertificates"],
  deps = [
    ":grpc_objc",
    ":rx_library",
  ],
)

objc_bundle_library(
    # The choice of name is signicant here, since it determines the bundle name.
    name = "gRPCCertificates",
    resources = ["etc/roots.pem"],
)

proto_objc_rpc_path = objc_path + "/ProtoRPC"

objc_library(
  name = "proto_objc_rpc",
  hdrs = glob([
    proto_objc_rpc_path + "/*.h",
  ]),
  srcs = glob([
    proto_objc_rpc_path + "/*.m",
  ]),
  includes = [objc_path],
  deps = [
    ":grpc_client",
    ":rx_library",
    "//external:protobuf_objc",
  ],
)
