steps:
#- name: 'ubuntu'
#  args: ['echo', 'hello world']
- id: 'fetch_submodules'
  name: 'gcr.io/cloud-builders/git'
  args: ['submodule', 'update', '--init']
- id: 'run_tests_py'
  name: 'grpctesting/csharp_stretch_x64:c53aee62cc5feb5358c5a8bb21e154711794aa96'
  args: ['python', 'tools/run_tests/run_tests.py', '-l', 'csharp', '-c', 'opt', '--build_only', '-j8', '-x', 'sponge_log.xml']
timeout: 1800s
options:
  machineType: 'N1_HIGHCPU_8'
#tags: ['basictests', 'csharp', 'linux', 'opt']
artifacts:
  objects:
    location: 'gs://grpc-testing-cloudbuild-public-logs/experimental_build_artifacts/artifacts-$BUILD_ID'
    paths: ['**sponge_log.xml']
logsBucket: 'grpc-testing-cloudbuild-public-logs/experimental_build_logs'
