steps:
- id: 'fetch_submodules'
  # TODO: for pull requests, the "as-if-merged" version or the PR should be tested first
  name: 'gcr.io/cloud-builders/git'
  args: ['submodule', 'update', '--init']
- id: 'run_tests_py'
  name: 'grpctesting/cloud_build_base:3f60b05a5d37e6f10cceeecad9ad50bc9eb45eff'  # modified version of gcr.io/cloud-builders/docker
  # run docker inside docker
  #name: 'grpctesting/csharp_stretch_x64:c53aee62cc5feb5358c5a8bb21e154711794aa96'
  args: ['python', 'tools/run_tests/run_tests.py', '-l', 'csharp', '-c', 'opt', '-j8', '-x', 'sponge_log.xml', '--use_docker']
  env:
    - 'DOCKERHUB_ORGANIZATION=grpctesting'
timeout: 1800s
options:
  machineType: 'N1_HIGHCPU_8'
  logging: GCS_ONLY
#tags: ['basictests', 'csharp', 'linux', 'opt']
artifacts:
  objects:
    location: 'gs://grpc-testing-cloudbuild-public-logs/experimental_build_artifacts/artifacts-$BUILD_ID'
    paths: ['**sponge_log.xml']
logsBucket: 'grpc-testing-cloudbuild-public-logs/experimental_build_logs'
