---
kind: GCPBackendPolicy
apiVersion: networking.gke.io/v1
metadata:
  name: ${be_policy_name}
  namespace: ${namespace_name}
  labels:
    owner: xds-k8s-interop-test
spec:
  targetRef:
    group: ""
    kind: Service
    name: ${service_name}
  default:
    connectionDraining:
      drainingTimeoutSec: 600
...
