#!/bin/bash
# Copyright 2017 gRPC authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Source this rc script to prepare the environment for linux perf builds

# Need to increase open files limit and size for perf test
ulimit -n 32768
ulimit -c unlimited

# Performance PR testing needs GH API key and PR metadata to comment results
if [ -n "$KOKORO_GITHUB_PULL_REQUEST_NUMBER" ]; then
  set +x
  sudo apt-get install -y jq
  export ghprbTargetBranch=$(curl -s https://api.github.com/repos/grpc/grpc/pulls/$KOKORO_GITHUB_PULL_REQUEST_NUMBER | jq -r .base.ref)

  gsutil cp gs://grpc-testing-secrets/github_credentials/oauth_token.txt ~/
  # TODO(matt-kwong): rename this to GITHUB_OAUTH_TOKEN after Jenkins deprecation
  export JENKINS_OAUTH_TOKEN=$(cat ~/oauth_token.txt)
  export ghprbPullId=$KOKORO_GITHUB_PULL_REQUEST_NUMBER
  set -x
fi

sudo pip install tabulate

git submodule update --init
