#!/bin/bash
# Copyright 2017 gRPC authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Source this rc script to prepare the environment for linux perf builds

# Need to increase open files limit and size for perf test
ulimit -n 32768
ulimit -c unlimited

# Download non-core gRPC repos
git clone --recursive https://github.com/grpc/grpc-go ./../grpc-go
git clone --recursive https://github.com/grpc/grpc-java ./../grpc-java
git clone --recursive https://github.com/grpc/grpc-node ./../grpc-node

sudo pip install tabulate

# Set up Ruby
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
gem list bundler
gem install bundler --no-ri --no-rdoc

# Allow SSH to Kokoro performance workers without explicit key verification
gsutil cp gs://grpc-testing-secrets/grpc_kokoro_performance_ssh_keys/id_rsa ~/.ssh
echo -e 'Host grpc-kokoro-performance*\n\tStrictHostKeyChecking no' >> ~/.ssh/config
chmod 600 ~/.ssh/id_rsa ~/.ssh/config

git submodule update --init
