%YAML 1.2
--- |
  # Copyright 2015 gRPC authors.
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
  
  <%include file="../../python_stretch.include"/>
  <%include file="../../cxx_deps.include"/>
  #========================
  # Sanity test dependencies
  RUN apt-get update && apt-get -t buster install -y python3.7 python3-all-dev
  RUN curl https://bootstrap.pypa.io/get-pip.py | python3.7
  # Make Python 3.7 the default Python 3 version
  RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1
  RUN apt-get update && apt-get install -y ${"\\"}
        autoconf ${"\\"}
        automake ${"\\"}
        libtool ${"\\"}
        curl ${"\\"}
        shellcheck
  RUN python2 -m pip install simplejson mako virtualenv lxml
  RUN python3 -m pip install simplejson mako virtualenv lxml

  <%include file="../../clang5.include"/>
  <%include file="../../bazel.include"/>
  <%include file="../../buildifier.include"/>

  # Define the default command.
  CMD ["bash"]
