%YAML 1.2
--- |
  # Copyright 2015 gRPC authors.
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.

  FROM silkeh/clang:18-bookworm

  <%include file="../../apt_get_basic.include"/>

  RUN apt update && apt install -y python3 python3-pip && apt-get clean
  RUN mkdir -p ~/.config/pip
  RUN echo "[global]\nbreak-system-packages = true" > ~/.config/pip/pip.conf

  <%include file="../../gcp_api_libraries.include"/>
  <%include file="../../run_tests_addons.include"/>

  #========================
  # Sanity test dependencies

  RUN apt-get update && apt-get install -y ${"\\"}
        autoconf ${"\\"}
        automake ${"\\"}
        libtool ${"\\"}
        curl ${"\\"}
        shellcheck

  # otherwise clang-tidy will report missing <gtest/gtest.h> header
  RUN apt-get update && apt-get install -y libgtest-dev && apt-get clean

  RUN python3 -m pip install simplejson mako virtualenv lxml six

  # Upgrade Python's YAML library
  RUN python3 -m pip install --upgrade --ignore-installed PyYAML

  # Install prerequisites for the clang-tidy script
  RUN apt-get update && apt-get install -y jq git && apt-get clean

  <%include file="../../bazel.include"/>
  <%include file="../../buildifier.include"/>

  # Define the default command.
  CMD ["bash"]
