type: com.google.api.codegen.ConfigProto
config_schema_version: 2.0.0
# The settings of generated code in a specific language.
language_settings:
  java:
    package_name: com.google.cloud.tasks.v2beta3
  python:
    package_name: google.cloud.tasks_v2beta3.gapic
  go:
    package_name: cloud.google.com/go/cloudtasks/apiv2beta3
  csharp:
    package_name: Google.Cloud.Tasks.V2Beta3
  ruby:
    package_name: Google::Cloud::Tasks::V2beta3
  php:
    package_name: Google\Cloud\Tasks\V2beta3
  nodejs:
    package_name: tasks.v2beta3
