FROM python:3.9-slim-bookworm

RUN apt-get update -y && apt-get upgrade -y && apt-get install -y build-essential clang curl

WORKDIR /workdir

RUN ln -s /usr/bin/python3 /usr/bin/python
RUN mkdir /artifacts

COPY . .
RUN tools/bazel build -c dbg --config=python_defines //src/python/grpcio_tests/tests_py3_only/interop:xds_interop_server
RUN cp -rL /workdir/bazel-bin/src/python/grpcio_tests/tests_py3_only/interop/xds_interop_server* /artifacts/

ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

FROM python:3.9-slim-bookworm

ENV GRPC_VERBOSITY="DEBUG"
ENV GRPC_TRACE="xds_client,xds_resolver,xds_cluster_manager_lb,cds_lb,xds_cluster_resolver_lb,priority_lb,xds_cluster_impl_lb,weighted_target_lb"

RUN apt-get update -y \
    && apt-get install -y python3 \
    && apt-get -y autoremove \
    && rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/python3 /usr/bin/python

COPY --from=0 /artifacts ./

# tini serves as PID 1 and enables the server to properly respond to signals.
COPY --from=0 /tini /tini

ENTRYPOINT ["/tini", "-g", "-vv",  "--",  "/xds_interop_server"]
