# Copyright 2018 gRPC authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

licenses(["notice"])

exports_files([
    "bundle.pem",
    "test_roots/cert1.pem",
    "test_roots/cert2.pem",
    "test_roots/cert3.pem",
    "spiffe/spiffe_cert.pem",
    "spiffe/client_spiffebundle.json",
    "spiffe/test_bundles/spiffebundle.json",
    "spiffe/test_bundles/spiffebundle_empty_keys.json",
    "spiffe/test_bundles/server1_spiffe.pem",
    "spiffe/test_bundles/spiffebundle2.json",
    "spiffe/test_bundles/spiffebundle_corrupted_cert.json",
    "spiffe/test_bundles/spiffebundle_empty_string_key.json",
    "spiffe/test_bundles/spiffebundle_invalid_trustdomain.json",
    "spiffe/test_bundles/spiffebundle_malformed.json",
    "spiffe/test_bundles/spiffebundle_match_client_spiffe.json",
    "spiffe/test_bundles/spiffebundle_wrong_kid.json",
    "spiffe/test_bundles/spiffebundle_wrong_kty.json",
    "spiffe/test_bundles/spiffebundle_wrong_multi_certs.json",
    "spiffe/test_bundles/spiffebundle_wrong_root.json",
    "spiffe/test_bundles/spiffebundle_wrong_seq_type.json",
    "spiffe/test_bundles/spiffebundle_wrong_use.json",
    "spiffe/test_bundles/spiffe_cert.pem",
    "spiffe/test_bundles/spiffe_multi_uri_san_cert.pem",
    "spiffe/test_bundles/spiffe-openssl.cnf",
    "spiffe/test_bundles/spiffe_test.json",
])
