# Copyright 2021 gRPC authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM debian:13

RUN apt update && apt -y upgrade && apt install -y build-essential ccache curl git time wget zip && apt clean
{% include "../../git_avoid_dubious_ownership_error.include" %}
{% include "../../run_tests_python_deps_venv.include" %}
{% include "../../cxx_deps.include" %}
RUN clang --version | grep -Eq "clang version 19\.[0-9]+"
{% include "../../cxx_test_deps.include" %}
{% include "../../cmake.include" %}
{% include "../../run_tests_addons.include" %}

# Define the default command.
CMD ["bash"]
