# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: envoy/extensions/load_balancing_policies/load_aware_locality/v3/load_aware_locality.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'envoy/extensions/load_balancing_policies/load_aware_locality/v3/load_aware_locality.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from envoy.config.cluster.v3 import cluster_pb2 as envoy_dot_config_dot_cluster_dot_v3_dot_cluster__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from udpa.annotations import status_pb2 as udpa_dot_annotations_dot_status__pb2
from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nYenvoy/extensions/load_balancing_policies/load_aware_locality/v3/load_aware_locality.proto\x12?envoy.extensions.load_balancing_policies.load_aware_locality.v3\x1a%envoy/config/cluster/v3/cluster.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1dudpa/annotations/status.proto\x1a\x17validate/validate.proto\"\x9b\x05\n\x11LoadAwareLocality\x12W\n\x17\x65ndpoint_picking_policy\x18\x01 \x01(\x0b\x32,.envoy.config.cluster.v3.LoadBalancingPolicyB\x08\xfa\x42\x05\x8a\x01\x02\x10\x01\x12\x46\n\x14weight_update_period\x18\x02 \x01(\x0b\x32\x19.google.protobuf.DurationB\r\xfa\x42\n\xaa\x01\x07\x32\x05\x10\x80\xc2\xd7/\x12.\n&metric_names_for_computing_utilization\x18\x03 \x03(\t\x12]\n\x1eutilization_variance_threshold\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.DoubleValueB\x17\xfa\x42\x14\x12\x12\x19\x00\x00\x00\x00\x00\x00\xf0?)\x00\x00\x00\x00\x00\x00\x00\x00\x12\x44\n\x17smoothing_time_constant\x18\x05 \x01(\x0b\x32\x19.google.protobuf.DurationB\x08\xfa\x42\x05\xaa\x01\x02*\x00\x12T\n\x15remote_probe_fraction\x18\x06 \x01(\x0b\x32\x1c.google.protobuf.DoubleValueB\x17\xfa\x42\x14\x12\x12\x11\x00\x00\x00\x00\x00\x00\xf0?)\x00\x00\x00\x00\x00\x00\x00\x00\x12\x45\n\x18weight_expiration_period\x18\x07 \x01(\x0b\x32\x19.google.protobuf.DurationB\x08\xfa\x42\x05\xaa\x01\x02\x32\x00\x12:\n\x16\x65nable_oob_load_report\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12\x37\n\x14oob_reporting_period\x18\t \x01(\x0b\x32\x19.google.protobuf.DurationB\xef\x01\nMio.envoyproxy.envoy.extensions.load_balancing_policies.load_aware_locality.v3B\x16LoadAwareLocalityProtoP\x01Z|github.com/envoyproxy/go-control-plane/envoy/extensions/load_balancing_policies/load_aware_locality/v3;load_aware_localityv3\xba\x80\xc8\xd1\x06\x02\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'envoy.extensions.load_balancing_policies.load_aware_locality.v3.load_aware_locality_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nMio.envoyproxy.envoy.extensions.load_balancing_policies.load_aware_locality.v3B\026LoadAwareLocalityProtoP\001Z|github.com/envoyproxy/go-control-plane/envoy/extensions/load_balancing_policies/load_aware_locality/v3;load_aware_localityv3\272\200\310\321\006\002\020\002'
  _globals['_LOADAWARELOCALITY'].fields_by_name['endpoint_picking_policy']._loaded_options = None
  _globals['_LOADAWARELOCALITY'].fields_by_name['endpoint_picking_policy']._serialized_options = b'\372B\005\212\001\002\020\001'
  _globals['_LOADAWARELOCALITY'].fields_by_name['weight_update_period']._loaded_options = None
  _globals['_LOADAWARELOCALITY'].fields_by_name['weight_update_period']._serialized_options = b'\372B\n\252\001\0072\005\020\200\302\327/'
  _globals['_LOADAWARELOCALITY'].fields_by_name['utilization_variance_threshold']._loaded_options = None
  _globals['_LOADAWARELOCALITY'].fields_by_name['utilization_variance_threshold']._serialized_options = b'\372B\024\022\022\031\000\000\000\000\000\000\360?)\000\000\000\000\000\000\000\000'
  _globals['_LOADAWARELOCALITY'].fields_by_name['smoothing_time_constant']._loaded_options = None
  _globals['_LOADAWARELOCALITY'].fields_by_name['smoothing_time_constant']._serialized_options = b'\372B\005\252\001\002*\000'
  _globals['_LOADAWARELOCALITY'].fields_by_name['remote_probe_fraction']._loaded_options = None
  _globals['_LOADAWARELOCALITY'].fields_by_name['remote_probe_fraction']._serialized_options = b'\372B\024\022\022\021\000\000\000\000\000\000\360?)\000\000\000\000\000\000\000\000'
  _globals['_LOADAWARELOCALITY'].fields_by_name['weight_expiration_period']._loaded_options = None
  _globals['_LOADAWARELOCALITY'].fields_by_name['weight_expiration_period']._serialized_options = b'\372B\005\252\001\0022\000'
  _globals['_LOADAWARELOCALITY']._serialized_start=318
  _globals['_LOADAWARELOCALITY']._serialized_end=985
# @@protoc_insertion_point(module_scope)
