%YAML 1.2
--- |
  # Copyright 2018 The gRPC Authors
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.

  <%include file="../../python_stretch.include"/>

  RUN apt-get install -y jq zlib1g-dev libssl-dev

  RUN apt-get install -y jq build-essential libffi-dev

  RUN cd /tmp && ${'\\'}
    wget -q https://github.com/python/cpython/archive/v3.6.9.tar.gz && ${'\\'}
    tar xzvf v3.6.9.tar.gz && ${'\\'}
    cd cpython-3.6.9 && ${'\\'}
    ./configure && ${'\\'}
    make install

  RUN python3.6 -m ensurepip && ${'\\'}
      python3.6 -m pip install coverage

