# Copyright 2018 The gRPC Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM alpine:3.18

# Install Git and basic packages.
RUN apk update && apk add \
  autoconf \
  automake \
  bash \
  bzip2 \
  build-base \
  cmake \
  ccache \
  curl \
  gcc \
  git \
  libtool \
  linux-headers \
  make \
  perl \
  strace \
  python3-dev \
  py3-pip \
  unzip \
  wget \
  zip

{% include "../../git_avoid_dubious_ownership_error.include" %}

# Install Python packages from PyPI
RUN python3 -m pip install --upgrade pip==19.3.1

{% include "../../gcp_api_libraries.include" %}
{% include "../../ccache.include" %}
{% include "../../run_tests_addons.include" %}

