# Copyright 2016 gRPC authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM php:8-zts-bookworm

RUN apt-get update && apt-get install -y \
  autoconf automake build-essential git libtool curl \
  zlib1g-dev \
  && apt-get clean

{% include "../../git_avoid_dubious_ownership_error.include" %}
{% include "../../run_tests_python_deps_pep668.include" %}
{% include "../../php_common_deps.include" %}
{% include "../../cmake.include" %}
RUN apt-get update && apt-get install -y ccache && apt-get clean
{% include "../../run_tests_addons.include" %}
{% include "../../xds_interop_deps.include" %}

# Define the default command.
CMD ["bash"]
