# Copyright 2016 gRPC authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM debian:13

{% include "../../apt_get_basic.include" %}
{% include "../../run_tests_python_deps_pep668.include" %}

# Install default PHP (which is 8.4 in Debian 13)
RUN apt-get update && apt-get install -y php php-dev php-pear && apt-get clean

# Install PHPUnit (PHPUnit 11 is the stable version that supports PHP 8.4)
RUN wget https://phar.phpunit.de/phpunit-11.1.5.phar && \
    mv phpunit-11.1.5.phar /usr/local/bin/phpunit && \
    chmod +x /usr/local/bin/phpunit

{% include "../../php_valgrind.include" %}
{% include "../../cmake.include" %}
RUN apt-get update && apt-get install -y ccache && apt-get clean
{% include "../../run_tests_addons.include" %}

# Define the default command.
CMD ["bash"]

