# Copyright 2021 The gRPC Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM debian:13

{% include "../../apt_get_basic.include" %}
{% include "../../run_tests_python_deps_venv.include" %}
{% include "../../cmake.include" %}
{% include "../../run_tests_addons.include" %}
RUN apt update && apt upgrade -y

# Java
RUN apt-get install -y openjdk-21-jdk

# Install Android SDK

# AGP 8.13.2 use following default versions:
#
# - SDK Build Tools 35.0.0
# - ndk 27.0.12077973
#
# We choose ndk;29.0.14206865 to be consistent with helloworld app.
#
# See also https://developer.android.com/build/releases/agp-8-13-0-release-notes#8.13.2
ENV ANDROID_HOME=/opt/android-sdk
RUN mkdir -p $ANDROID_HOME && \
    wget -O cmd.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip && \
    unzip cmd.zip && rm cmd.zip && \
    yes | ./cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses && \
    ./cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME 'platform-tools' && \
    ./cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME 'build-tools;35.0.0' && \
    ./cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME 'platforms;android-26' && \
    ./cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME 'ndk;29.0.14206865' && \
    ./cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME 'cmake;3.22.1'

# Install gcloud
RUN wget -O google-cloud-cli.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-467.0.0-linux-x86_64.tar.gz && \
    tar -xf google-cloud-cli.tar.gz && \
    ./google-cloud-sdk/install.sh --bash-completion=false --path-update=true && \
    rm -rf google-cloud-cli.tar.gz
RUN ln -s /google-cloud-sdk/bin/gcloud /usr/local/bin/gcloud

# Define the default command.
CMD ["bash"]
