# Copyright 2015 gRPC authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM debian:jessie

# Install Git and basic packages.
RUN apt-get update && apt-get install -y \
  autoconf \
  autotools-dev \
  build-essential \
  bzip2 \
  ccache \
  curl \
  dnsutils \
  gcc \
  gcc-multilib \
  git \
  golang \
  gyp \
  lcov \
  libc6 \
  libc6-dbg \
  libc6-dev \
  libgtest-dev \
  libtool \
  make \
  perl \
  strace \
  python-dev \
  python-setuptools \
  python-yaml \
  telnet \
  unzip \
  wget \
  zip && apt-get clean

#================
# Build profiling
RUN apt-get update && apt-get install -y time && apt-get clean

#====================
# Python dependencies

# Install dependencies

RUN apt-get update && apt-get install -y \
    python-all-dev \
    python3-all-dev \
    python-pip

# Install Python packages from PyPI
RUN pip install --upgrade pip==19.3.1
RUN pip install virtualenv
RUN pip install futures==2.2.0 enum34==1.0.4 protobuf==3.5.2.post1 six==1.10.0 twisted==17.5.0

#=================
# C++ dependencies
RUN apt-get update && apt-get -y install libgflags-dev libgtest-dev libc++-dev clang && apt-get clean

#================
# Clone gRPC repo
RUN mkdir /grpc
RUN git clone --depth 1 https://github.com/grpc/grpc.git /grpc/grpc
WORKDIR /grpc/grpc
RUN git submodule update --init

#========================
# Build performance tests
RUN python tools/run_tests/run_tests.py -l c++ --build_only

#=====================================
# Clean everything aside from binaries
RUN rm -r "$(ls --hide=bins --hide=bazel --hide=gens --hide=include --hide=objs --hide=tools --hide=test)"

#=======================
# Run performance worker
ENV DRIVER_PORT=10000
ENV WORKER_KIND=client
ENV SERVER_PORT=10010
COPY run.sh .
RUN chmod a+x run.sh
EXPOSE 32766
EXPOSE $DRIVER_PORT
CMD ["./run.sh"]

