#!/bin/bash
echo "Testing ${docker_image:=grpc_interop_go:dd8fbf3a-4964-4387-9997-5dadeea09835}"
docker run --rm=true --net=host $docker_image /go/bin/client --server_host=grpc-test.sandbox.googleapis.com --server_port=443 --use_tls=true --test_case=large_unary
docker run --rm=true --net=host $docker_image /go/bin/client --server_host=grpc-test.sandbox.googleapis.com --server_port=443 --use_tls=true --test_case=empty_unary
docker run --rm=true --net=host $docker_image /go/bin/client --server_host=grpc-test.sandbox.googleapis.com --server_port=443 --use_tls=true --test_case=ping_pong
docker run --rm=true --net=host $docker_image /go/bin/client --server_host=grpc-test.sandbox.googleapis.com --server_port=443 --use_tls=true --test_case=empty_stream
docker run --rm=true --net=host $docker_image /go/bin/client --server_host=grpc-test.sandbox.googleapis.com --server_port=443 --use_tls=true --test_case=client_streaming
docker run --rm=true --net=host $docker_image /go/bin/client --server_host=grpc-test.sandbox.googleapis.com --server_port=443 --use_tls=true --test_case=server_streaming
docker run --rm=true --net=host $docker_image /go/bin/client --server_host=grpc-test.sandbox.googleapis.com --server_port=443 --use_tls=true --test_case=cancel_after_begin
docker run --rm=true --net=host $docker_image /go/bin/client --server_host=grpc-test.sandbox.googleapis.com --server_port=443 --use_tls=true --test_case=cancel_after_first_response
docker run --rm=true --net=host $docker_image /go/bin/client --server_host=grpc-test.sandbox.googleapis.com --server_port=443 --use_tls=true --test_case=timeout_on_sleeping_server
docker run --rm=true --net=host $docker_image /go/bin/client --server_host=grpc-test4.sandbox.googleapis.com --server_port=443 --use_tls=true --test_case=large_unary
docker run --rm=true --net=host $docker_image /go/bin/client --server_host=grpc-test4.sandbox.googleapis.com --server_port=443 --use_tls=true --test_case=empty_unary
docker run --rm=true --net=host $docker_image /go/bin/client --server_host=grpc-test4.sandbox.googleapis.com --server_port=443 --use_tls=true --test_case=ping_pong
docker run --rm=true --net=host $docker_image /go/bin/client --server_host=grpc-test4.sandbox.googleapis.com --server_port=443 --use_tls=true --test_case=empty_stream
docker run --rm=true --net=host $docker_image /go/bin/client --server_host=grpc-test4.sandbox.googleapis.com --server_port=443 --use_tls=true --test_case=client_streaming
docker run --rm=true --net=host $docker_image /go/bin/client --server_host=grpc-test4.sandbox.googleapis.com --server_port=443 --use_tls=true --test_case=server_streaming
docker run --rm=true --net=host $docker_image /go/bin/client --server_host=grpc-test4.sandbox.googleapis.com --server_port=443 --use_tls=true --test_case=cancel_after_begin
docker run --rm=true --net=host $docker_image /go/bin/client --server_host=grpc-test4.sandbox.googleapis.com --server_port=443 --use_tls=true --test_case=cancel_after_first_response
docker run --rm=true --net=host $docker_image /go/bin/client --server_host=grpc-test4.sandbox.googleapis.com --server_port=443 --use_tls=true --test_case=timeout_on_sleeping_server
