FUNCTION(GRPC_PB_GENERATE_CPP SRCS HDRS PROTO)
	SET(PROTOROOT ${CMAKE_CURRENT_SOURCE_DIR})

	GET_FILENAME_COMPONENT(ABS_FILE ${PROTO} ABSOLUTE)
	GET_FILENAME_COMPONENT(FILE_WE ${PROTO} NAME_WE)

	# build the result filename
	SET(CPP_FILE "${OUTPATH}/${FILE_WE}.grpc.pb.cc")
	SET(H_FILE "${OUTPATH}/${FILE_WE}.grpc.pb.h")
	LIST(APPEND ${SRCS} "${CPP_FILE}")
	LIST(APPEND ${HDRS} "${H_FILE}")

    SET(${SRCS})
    SET(${HDRS})

	ADD_CUSTOM_COMMAND(
		OUTPUT "${CPP_FILE}"
		       "${H_FILE}"
		COMMAND ${CMAKE_COMMAND} -E make_directory ${OUTPATH}
		COMMAND ${PROTOBUF_PROTOC_EXECUTABLE}
		ARGS "--grpc_out=${OUTPATH}" --proto_path "${PROTOROOT}" "${MATCH_PATH}"
		COMMENT "Running gRPC C++ protocol buffer compiler on ${MATCH_PATH} with root ${PROTOROOT}, generating ${CPP_FILE}"
		VERBATIM)

	SET_SOURCE_FILES_PROPERTIES(${${SRCS}} ${${HDRS}} PROPERTIES GENERATED TRUE)
	SET(${SRCS} ${${SRCS}} PARENT_SCOPE)
	SET(${HDRS} ${${HDRS}} PARENT_SCOPE)
ENDFUNCTION()

