var searchData=
[
  ['serializationtraits',['SerializationTraits',['../classgrpc_1_1_serialization_traits.html',1,'grpc']]],
  ['serializationtraits_3c_20bytebuffer_2c_20void_20_3e',['SerializationTraits&lt; ByteBuffer, void &gt;',['../classgrpc_1_1_serialization_traits_3_01_byte_buffer_00_01void_01_4.html',1,'grpc']]],
  ['serializationtraits_3c_20t_2c_20typename_20std_3a_3aenable_5fif_3c_20std_3a_3ais_5fbase_5fof_3c_20grpc_3a_3aprotobuf_3a_3amessage_2c_20t_20_3e_3a_3avalue_20_3e_3a_3atype_20_3e',['SerializationTraits&lt; T, typename std::enable_if&lt; std::is_base_of&lt; grpc::protobuf::Message, T &gt;::value &gt;::type &gt;',['../classgrpc_1_1_serialization_traits_3_01_t_00_01typename_01std_1_1enable__if_3_01std_1_1is__base_42903f95c85f031c7724191271564901.html',1,'grpc']]],
  ['server',['Server',['../classgrpc_1_1_server.html',1,'grpc']]],
  ['serverasyncreader',['ServerAsyncReader',['../classgrpc_1_1_server_async_reader.html',1,'grpc']]],
  ['serverasyncreaderinterface',['ServerAsyncReaderInterface',['../classgrpc_1_1_server_async_reader_interface.html',1,'grpc']]],
  ['serverasyncreaderwriter',['ServerAsyncReaderWriter',['../classgrpc_1_1_server_async_reader_writer.html',1,'grpc']]],
  ['serverasyncreaderwriterinterface',['ServerAsyncReaderWriterInterface',['../classgrpc_1_1_server_async_reader_writer_interface.html',1,'grpc']]],
  ['serverasyncresponsewriter',['ServerAsyncResponseWriter',['../classgrpc_1_1_server_async_response_writer.html',1,'grpc']]],
  ['serverasyncstreaminginterface',['ServerAsyncStreamingInterface',['../classgrpc_1_1_server_async_streaming_interface.html',1,'grpc']]],
  ['serverasyncwriter',['ServerAsyncWriter',['../classgrpc_1_1_server_async_writer.html',1,'grpc']]],
  ['serverasyncwriterinterface',['ServerAsyncWriterInterface',['../classgrpc_1_1_server_async_writer_interface.html',1,'grpc']]],
  ['serverbuilder',['ServerBuilder',['../classgrpc_1_1_server_builder.html',1,'grpc']]],
  ['serverbuilderoption',['ServerBuilderOption',['../classgrpc_1_1_server_builder_option.html',1,'grpc']]],
  ['serverbuilderplugin',['ServerBuilderPlugin',['../classgrpc_1_1_server_builder_plugin.html',1,'grpc']]],
  ['servercompletionqueue',['ServerCompletionQueue',['../classgrpc_1_1_server_completion_queue.html',1,'grpc']]],
  ['servercontext',['ServerContext',['../classgrpc_1_1_server_context.html',1,'grpc']]],
  ['servercredentials',['ServerCredentials',['../classgrpc_1_1_server_credentials.html',1,'grpc']]],
  ['serverinitializer',['ServerInitializer',['../classgrpc_1_1_server_initializer.html',1,'grpc']]],
  ['serverinterface',['ServerInterface',['../classgrpc_1_1_server_interface.html',1,'grpc']]],
  ['serverreader',['ServerReader',['../classgrpc_1_1_server_reader.html',1,'grpc']]],
  ['serverreaderinterface',['ServerReaderInterface',['../classgrpc_1_1_server_reader_interface.html',1,'grpc']]],
  ['serverreaderwriter',['ServerReaderWriter',['../classgrpc_1_1_server_reader_writer.html',1,'grpc']]],
  ['serverreaderwriterbody',['ServerReaderWriterBody',['../classgrpc_1_1internal_1_1_server_reader_writer_body.html',1,'grpc::internal']]],
  ['serverreaderwriterbody_3c_20responsetype_2c_20requesttype_20_3e',['ServerReaderWriterBody&lt; ResponseType, RequestType &gt;',['../classgrpc_1_1internal_1_1_server_reader_writer_body.html',1,'grpc::internal']]],
  ['serverreaderwriterinterface',['ServerReaderWriterInterface',['../classgrpc_1_1_server_reader_writer_interface.html',1,'grpc']]],
  ['serverreaderwriterinterface_3c_20responsetype_2c_20requesttype_20_3e',['ServerReaderWriterInterface&lt; ResponseType, RequestType &gt;',['../classgrpc_1_1_server_reader_writer_interface.html',1,'grpc']]],
  ['serversplitstreamer',['ServerSplitStreamer',['../classgrpc_1_1_server_split_streamer.html',1,'grpc']]],
  ['serverstreaminghandler',['ServerStreamingHandler',['../classgrpc_1_1_server_streaming_handler.html',1,'grpc']]],
  ['serverstreaminginterface',['ServerStreamingInterface',['../classgrpc_1_1_server_streaming_interface.html',1,'grpc']]],
  ['serverunarystreamer',['ServerUnaryStreamer',['../classgrpc_1_1_server_unary_streamer.html',1,'grpc']]],
  ['serverwriter',['ServerWriter',['../classgrpc_1_1_server_writer.html',1,'grpc']]],
  ['serverwriterinterface',['ServerWriterInterface',['../classgrpc_1_1_server_writer_interface.html',1,'grpc']]],
  ['service',['Service',['../classgrpc_1_1_service.html',1,'grpc']]],
  ['slice',['Slice',['../classgrpc_1_1_slice.html',1,'grpc']]],
  ['sneakycallopset',['SneakyCallOpSet',['../classgrpc_1_1_sneaky_call_op_set.html',1,'grpc']]],
  ['sneakycallopset_3c_20grpc_3a_3acallopsendinitialmetadata_2c_20grpc_3a_3acallopsendmessage_2c_20grpc_3a_3acallopclientsendclose_20_3e',['SneakyCallOpSet&lt; grpc::CallOpSendInitialMetadata, grpc::CallOpSendMessage, grpc::CallOpClientSendClose &gt;',['../classgrpc_1_1_sneaky_call_op_set.html',1,'grpc']]],
  ['splitserverstreaminghandler',['SplitServerStreamingHandler',['../classgrpc_1_1_split_server_streaming_handler.html',1,'grpc']]],
  ['sslcredentialsoptions',['SslCredentialsOptions',['../structgrpc_1_1_ssl_credentials_options.html',1,'grpc']]],
  ['sslservercredentialsoptions',['SslServerCredentialsOptions',['../structgrpc_1_1_ssl_server_credentials_options.html',1,'grpc']]],
  ['status',['Status',['../classgrpc_1_1_status.html',1,'grpc']]],
  ['streamedunaryhandler',['StreamedUnaryHandler',['../classgrpc_1_1_streamed_unary_handler.html',1,'grpc']]],
  ['string_5fref',['string_ref',['../classgrpc_1_1string__ref.html',1,'grpc']]],
  ['stuboptions',['StubOptions',['../classgrpc_1_1_stub_options.html',1,'grpc']]]
];
