/* This file was generated by upbc (the upb compiler) from the input
 * file:
 *
 *     envoy/api/v2/endpoint/load_report.proto
 *
 * Do not edit -- your changes will be discarded when the file is
 * regenerated. */

#include "upb/def.h"

extern upb_def_init envoy_api_v2_core_address_proto_upbdefinit;
extern upb_def_init envoy_api_v2_core_base_proto_upbdefinit;
extern upb_def_init google_protobuf_duration_proto_upbdefinit;
extern upb_def_init google_protobuf_struct_proto_upbdefinit;
extern upb_def_init validate_validate_proto_upbdefinit;
extern upb_def_init gogoproto_gogo_proto_upbdefinit;
static const char descriptor[2008] =
"\n\'envoy/api/v2/endpoint/load_report.prot"
"o\022\025envoy.api.v2.endpoint\032\037envoy/api/v2/c"
"ore/address.proto\032\034envoy/api/v2/core/bas"
"e.proto\032\036google/protobuf/duration.proto\032"
"\034google/protobuf/struct.proto\032\027validate/"
"validate.proto\032\024gogoproto/gogo.proto\"\215\004\n"
"\025UpstreamLocalityStats\0227\n\010locality\030\001 \001(\013"
"2\033.envoy.api.v2.core.LocalityR\010locality\022"
":\n\031total_successful_requests\030\002 \001(\004R\027tota"
"lSuccessfulRequests\022;\n\032total_requests_in"
"_progress\030\003 \001(\004R\027totalRequestsInProgress"
"\0220\n\024total_error_requests\030\004 \001(\004R\022totalErr"
"orRequests\0222\n\025total_issued_requests\030\010 \001("
"\004R\023totalIssuedRequests\022Z\n\021load_metric_st"
"ats\030\005 \003(\0132..envoy.api.v2.endpoint.Endpoi"
"ntLoadMetricStatsR\017loadMetricStats\022d\n\027up"
"stream_endpoint_stats\030\007 \003(\0132,.envoy.api."
"v2.endpoint.UpstreamEndpointStatsR\025upstr"
"eamEndpointStats\022\032\n\010priority\030\006 \001(\rR\010prio"
"rity\"\275\003\n\025UpstreamEndpointStats\0224\n\007addres"
"s\030\001 \001(\0132\032.envoy.api.v2.core.AddressR\007add"
"ress\0223\n\010metadata\030\006 \001(\0132\027.google.protobuf"
".StructR\010metadata\022:\n\031total_successful_re"
"quests\030\002 \001(\004R\027totalSuccessfulRequests\022;\n"
"\032total_requests_in_progress\030\003 \001(\004R\027total"
"RequestsInProgress\0220\n\024total_error_reques"
"ts\030\004 \001(\004R\022totalErrorRequests\0222\n\025total_is"
"sued_requests\030\007 \001(\004R\023totalIssuedRequests"
"\022Z\n\021load_metric_stats\030\005 \003(\0132..envoy.api."
"v2.endpoint.EndpointLoadMetricStatsR\017loa"
"dMetricStats\"\262\001\n\027EndpointLoadMetricStats"
"\022\037\n\013metric_name\030\001 \001(\tR\nmetricName\022H\n!num"
"_requests_finished_with_metric\030\002 \001(\004R\035nu"
"mRequestsFinishedWithMetric\022,\n\022total_met"
"ric_value\030\003 \001(\001R\020totalMetricValue\"\242\004\n\014Cl"
"usterStats\022,\n\014cluster_name\030\001 \001(\tB\t\272\351\300\003\004r"
"\002 \001R\013clusterName\0220\n\024cluster_service_name"
"\030\006 \001(\tR\022clusterServiceName\022p\n\027upstream_l"
"ocality_stats\030\002 \003(\0132,.envoy.api.v2.endpo"
"int.UpstreamLocalityStatsB\n\272\351\300\003\005\222\001\002\010\001R\025u"
"pstreamLocalityStats\0224\n\026total_dropped_re"
"quests\030\003 \001(\004R\024totalDroppedRequests\022^\n\020dr"
"opped_requests\030\005 \003(\01323.envoy.api.v2.endp"
"oint.ClusterStats.DroppedRequestsR\017dropp"
"edRequests\022K\n\024load_report_interval\030\004 \001(\013"
"2\031.google.protobuf.DurationR\022loadReportI"
"nterval\032]\n\017DroppedRequests\022%\n\010category\030\001"
" \001(\tB\t\272\351\300\003\004r\002 \001R\010category\022#\n\rdropped_cou"
"nt\030\002 \001(\004R\014droppedCountB8\n#io.envoyproxy."
"envoy.api.v2.endpointB\017LoadReportProtoP\001"
"b\006proto3"
;
static upb_def_init *deps[7] = {
  &envoy_api_v2_core_address_proto_upbdefinit,
  &envoy_api_v2_core_base_proto_upbdefinit,
  &google_protobuf_duration_proto_upbdefinit,
  &google_protobuf_struct_proto_upbdefinit,
  &validate_validate_proto_upbdefinit,
  &gogoproto_gogo_proto_upbdefinit,
  NULL
};
upb_def_init envoy_api_v2_endpoint_load_report_proto_upbdefinit = {
  deps,
  "envoy/api/v2/endpoint/load_report.proto",
  UPB_STRVIEW_INIT(descriptor, 2008)
};
