# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: envoy/extensions/rbac/principals/mtls_authenticated/v3/mtls_authenticated.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'envoy/extensions/rbac/principals/mtls_authenticated/v3/mtls_authenticated.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from envoy.extensions.transport_sockets.tls.v3 import common_pb2 as envoy_dot_extensions_dot_transport__sockets_dot_tls_dot_v3_dot_common__pb2
from udpa.annotations import status_pb2 as udpa_dot_annotations_dot_status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nOenvoy/extensions/rbac/principals/mtls_authenticated/v3/mtls_authenticated.proto\x12\x36\x65nvoy.extensions.rbac.principals.mtls_authenticated.v3\x1a\x36\x65nvoy/extensions/transport_sockets/tls/v3/common.proto\x1a\x1dudpa/annotations/status.proto\"\x89\x01\n\x06\x43onfig\x12U\n\x0bsan_matcher\x18\x01 \x01(\x0b\x32@.envoy.extensions.transport_sockets.tls.v3.SubjectAltNameMatcher\x12(\n any_validated_client_certificate\x18\x02 \x01(\x08\x42\xdc\x01\nDio.envoyproxy.envoy.extensions.rbac.principals.mtls_authenticated.v3B\x16MtlsAuthenticatedProtoP\x01Zrgithub.com/envoyproxy/go-control-plane/envoy/extensions/rbac/principals/mtls_authenticated/v3;mtls_authenticatedv3\xba\x80\xc8\xd1\x06\x02\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'envoy.extensions.rbac.principals.mtls_authenticated.v3.mtls_authenticated_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nDio.envoyproxy.envoy.extensions.rbac.principals.mtls_authenticated.v3B\026MtlsAuthenticatedProtoP\001Zrgithub.com/envoyproxy/go-control-plane/envoy/extensions/rbac/principals/mtls_authenticated/v3;mtls_authenticatedv3\272\200\310\321\006\002\020\002'
  _globals['_CONFIG']._serialized_start=227
  _globals['_CONFIG']._serialized_end=364
# @@protoc_insertion_point(module_scope)
