apiVersion: e2etest.grpc.io/v1
kind: LoadTest
metadata:
  annotations:
    test_infra_tag: v0.5.0
  name: basic_template
spec:
  clients:
  - build:
      command:
      - bash
      - /build_scripts/build_qps_worker.sh
    clone:
      gitRef: master
      repo: https://github.com/grpc/grpc.git
    language: csharp
    run:
      args:
      - exec
      - qps_worker/Grpc.IntegrationTesting.QpsWorker.dll
      command:
      - dotnet
  - build:
      args:
      - build
      - //test/cpp/qps:qps_worker
      command:
      - bazel
    clone:
      gitRef: master
      repo: https://github.com/grpc/grpc.git
    language: cxx
    run:
      command:
      - bazel-bin/test/cpp/qps/qps_worker
  - build:
      args:
      - build
      - -o
      - /src/workspace/bin/worker
      - ./benchmark/worker
      command:
      - go
    clone:
      gitRef: master
      repo: https://github.com/grpc/grpc-go.git
    language: go
    run:
      command:
      - /src/workspace/bin/worker
  - build:
      args:
      - -PskipAndroid=true
      - -PskipCodegen=true
      - :grpc-benchmarks:installDist
      command:
      - gradle
    clone:
      gitRef: master
      repo: https://github.com/grpc/grpc-java.git
    language: java
    run:
      command:
      - benchmarks/build/install/grpc-benchmarks/bin/benchmark_worker
  - build:
      command:
      - bash
      - /build_scripts/build_qps_worker.sh
    clone:
      gitRef: master
      repo: https://github.com/grpc/grpc-node.git
    language: node
    run:
      args:
      - -r
      - ./test/fixtures/native_native.js
      - test/performance/worker.js
      - --benchmark_impl=grpc
      command:
      - node
  - build:
      command:
      - bash
      - /build_scripts/build_qps_worker.sh
    clone:
      gitRef: master
      repo: https://github.com/grpc/grpc.git
    language: php
    run:
      command:
      - bash
      - /run_scripts/run_worker.sh
  - build:
      args:
      - build
      - //src/python/grpcio_tests/tests/qps:qps_worker
      command:
      - bazel
    clone:
      gitRef: master
      repo: https://github.com/grpc/grpc.git
    language: python
    run:
      command:
      - bazel-bin/src/python/grpcio_tests/tests/qps/qps_worker
  - build:
      command:
      - bash
      - /build_scripts/build_qps_worker.sh
    clone:
      gitRef: master
      repo: https://github.com/grpc/grpc
    language: ruby
    run:
      args:
      - src/ruby/qps/worker.rb
      command:
      - ruby
  servers:
  - build:
      command:
      - bash
      - /build_scripts/build_qps_worker.sh
    clone:
      gitRef: master
      repo: https://github.com/grpc/grpc.git
    language: csharp
    run:
      args:
      - exec
      - qps_worker/Grpc.IntegrationTesting.QpsWorker.dll
      command:
      - dotnet
  - build:
      args:
      - build
      - //test/cpp/qps:qps_worker
      command:
      - bazel
    clone:
      gitRef: master
      repo: https://github.com/grpc/grpc.git
    language: cxx
    run:
      args:
      - --server_port=10010
      command:
      - bazel-bin/test/cpp/qps/qps_worker
  - build:
      args:
      - build
      - -o
      - /src/workspace/bin/worker
      - ./benchmark/worker
      command:
      - go
    clone:
      gitRef: master
      repo: https://github.com/grpc/grpc-go.git
    language: go
    run:
      command:
      - /src/workspace/bin/worker
  - build:
      args:
      - -PskipAndroid=true
      - -PskipCodegen=true
      - :grpc-benchmarks:installDist
      command:
      - gradle
    clone:
      gitRef: master
      repo: https://github.com/grpc/grpc-java.git
    language: java
    run:
      command:
      - benchmarks/build/install/grpc-benchmarks/bin/benchmark_worker
  - build:
      command:
      - bash
      - /build_scripts/build_qps_worker.sh
    clone:
      gitRef: master
      repo: https://github.com/grpc/grpc-node.git
    language: node
    run:
      args:
      - -r
      - ./test/fixtures/native_native.js
      - test/performance/worker.js
      - --benchmark_impl=grpc
      command:
      - node
  - build:
      command:
      - bash
      - /build_scripts/build_qps_worker.sh
    clone:
      gitRef: master
      repo: https://github.com/grpc/grpc.git
    language: php
    run:
      command:
      - bash
      - /run_scripts/run_worker.sh
  - build:
      args:
      - build
      - //src/python/grpcio_tests/tests/qps:qps_worker
      command:
      - bazel
    clone:
      gitRef: master
      repo: https://github.com/grpc/grpc.git
    language: python
    run:
      command:
      - bazel-bin/src/python/grpcio_tests/tests/qps/qps_worker
  - build:
      command:
      - bash
      - /build_scripts/build_qps_worker.sh
    clone:
      gitRef: master
      repo: https://github.com/grpc/grpc
    language: ruby
    run:
      args:
      - src/ruby/qps/worker.rb
      command:
      - ruby
  timeoutSeconds: 900
  ttlSeconds: 86400
