[build-system]
requires = [
    "setuptools>=40.8.0",
    "wheel",
    "cython>=3.1.1",
]
build-backend = "setuptools.build_meta"

[project]
name = "grpcio-tools"
dynamic = ["version", "dependencies"]
description = "Protobuf code generator for gRPC"
readme = {file = "README.rst", content-type = "text/x-rst"}
authors = [
    {name = "The gRPC Authors", email = "grpc-io@googlegroups.com"}
]
license = {text = "Apache License 2.0"}
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
requires-python = ">=3.9"

[project.urls]
Homepage = "https://grpc.io"
"Source Code" = "https://github.com/grpc/grpc/tree/master/tools/distrib/python/grpcio_tools"
"Bug Tracker" = "https://github.com/grpc/grpc/issues"

[project.scripts]
"python-grpc-tools-protoc" = "grpc_tools.protoc:entrypoint"

[tool.setuptools.dynamic]
version = {attr = "grpc_version.VERSION"}
dependencies = {attr = "setup.install_requires"}
