[build-system]
requires = ["setuptools>=61.0.0", "wheel", "cython>=3.1.1"]
build-backend = "setuptools.build_meta"

[project]
name = "grpcio-tools"
version = "1.76.0.dev0"
description = "Protobuf code generator for gRPC"
readme = "README.rst"
requires-python = ">=3.9"
license = {text = "Apache License 2.0"}
keywords = ["grpc", "protobuf", "rpc"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

authors = [
    { name = "The gRPC Authors", email = "grpc-io@googlegroups.com" }
]

dependencies = [
    "protobuf>=6.31.1,<7.0.0",
    "setuptools",
]

# Entry points are defined in setup.py to avoid conflicts
# [project.scripts]
# "python-grpc-tools-protoc" = "grpc_tools.protoc:entrypoint"

[project.urls]
Homepage = "https://grpc.io"
Repository = "https://github.com/grpc/grpc"
"Source Code" = "https://github.com/grpc/grpc/tree/master/tools/distrib/python/grpcio_tools"
"Bug Tracker" = "https://github.com/grpc/grpc/issues"

[tool.setuptools]
# Use the setup.py functions for complex extension module configuration
# The ext-modules will be provided by get_ext_modules() function in setup.py
package-data = {grpc_tools = ["_proto/*"]}

[tool.setuptools.dynamic]
version = {attr = "grpc_version.VERSION"}

[tool.setuptools.packages.find]
where = ["."]
include = ["grpc_tools*"]