# Copyright 2026 the gRPC authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM debian:12

{% include "../../apt_get_basic.include" %}
{% include "../../run_tests_python_deps_pep668.include" %}
{% include "../../cxx_test_deps.include" %}
{% include "../../cxx_deps.include" %}
{% include "../../cmake.include" %}
{% include "../../ccache.include" %}
{% include "../../run_tests_addons.include" %}

# Install openssl 4.0.0 from source
RUN apt-get update && apt-get install -y build-essential zlib1g-dev && apt-get clean
RUN cd /tmp && \
    curl -sSL --fail --retry 5 -o openssl-4.0.0.tar.gz https://github.com/openssl/openssl/releases/download/openssl-4.0.0/openssl-4.0.0.tar.gz && \
    tar -xf openssl-4.0.0.tar.gz && \
    cd openssl-4.0.0 && \
    ./config --prefix=/usr/local/ssl --openssldir=/usr/local/ssl --libdir=lib shared zlib && \
    make -j4 && \
    make install_sw && \
    echo "/usr/local/ssl/lib" > /etc/ld.so.conf.d/openssl.conf && \
    ldconfig && \
    rm -rf /tmp/openssl-4.0.0*
ENV OPENSSL_ROOT_DIR=/usr/local/ssl

# Define the default command.
CMD ["bash"]
