[build-system]
requires = [
    "setuptools>=77.0.1",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "grpcio-testing"
license = "Apache-2.0"
description = "Testing utilities for gRPC Python"
readme = {file = "README.rst", content-type = "text/x-rst"} # adding content-type resolves twine check warnings during release upload
authors = [{name = "The gRPC Authors", email = "grpc-io@googlegroups.com"}]

dynamic = ["dependencies", "requires-python", "version", "classifers"]

[project.urls]
Homepage = "https://grpc.io"

[tool.setuptools.packages]
find = {}

[tool.setuptools.dynamic]
version = {attr = "grpc_version.VERSION"}

[tool.setuptools.package-dir]
"" = "."
