/* This file was generated by upb_generator from the input file:
 *
 *     grpc/health/v1/health.proto
 *
 * Do not edit -- your changes will be discarded when the file is
 * regenerated.
 * NO CHECKED-IN PROTOBUF GENCODE */

#include <stddef.h>
#include "upb/generated_code_support.h"
#include "grpc/health/v1/health.upb_minitable.h"

// Must be last.
#include "upb/port/def.inc"

extern const UPB_PRIVATE(upb_GeneratedExtensionListEntry)* UPB_PRIVATE(upb_generated_extension_list);
typedef struct {
  upb_MiniTableField fields[1];
} grpc__health__v1__HealthCheckRequest_msg_init_Fields;

static const grpc__health__v1__HealthCheckRequest_msg_init_Fields grpc_health_v1_HealthCheckRequest__fields = {{
  {1, 8, 0, kUpb_NoSub, 9, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
}};

const upb_MiniTable grpc__health__v1__HealthCheckRequest_msg_init = {
  &grpc_health_v1_HealthCheckRequest__fields.fields[0],
  UPB_SIZE(16, 24), 1, kUpb_ExtMode_NonExtendable, 1, UPB_FASTTABLE_MASK(8), 0,
#ifdef UPB_TRACING_ENABLED
  "grpc.health.v1.HealthCheckRequest",
#endif
  UPB_FASTTABLE_INIT({
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x000800003f00000a, &upb_DecodeFast_String_Scalar_Tag1Byte},
  })
};

typedef struct {
  upb_MiniTableField fields[1];
} grpc__health__v1__HealthCheckResponse_msg_init_Fields;

static const grpc__health__v1__HealthCheckResponse_msg_init_Fields grpc_health_v1_HealthCheckResponse__fields = {{
  {1, 8, 0, kUpb_NoSub, 5, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
}};

const upb_MiniTable grpc__health__v1__HealthCheckResponse_msg_init = {
  &grpc_health_v1_HealthCheckResponse__fields.fields[0],
  16, 1, kUpb_ExtMode_NonExtendable, 1, UPB_FASTTABLE_MASK(8), 0,
#ifdef UPB_TRACING_ENABLED
  "grpc.health.v1.HealthCheckResponse",
#endif
  UPB_FASTTABLE_INIT({
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x000800003f000008, &upb_DecodeFast_Varint32_Scalar_Tag1Byte},
  })
};

const upb_MiniTable grpc__health__v1__HealthListRequest_msg_init = {
  NULL,
  8, 0, kUpb_ExtMode_NonExtendable, 0, UPB_FASTTABLE_MASK(255), 0,
#ifdef UPB_TRACING_ENABLED
  "grpc.health.v1.HealthListRequest",
#endif
};

typedef struct {
  upb_MiniTableField fields[1];
  upb_MiniTableSubInternal subs[1];
} grpc__health__v1__HealthListResponse_msg_init_Fields;

static const grpc__health__v1__HealthListResponse_msg_init_Fields grpc_health_v1_HealthListResponse__fields = {{
  {1, 8, 0, UPB_SIZE(3, 4), 11, (int)kUpb_FieldMode_Map | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
 },
  {
  {.UPB_PRIVATE(submsg) = &grpc__health__v1__HealthListResponse__StatusesEntry_msg_init},
}};

const upb_MiniTable grpc__health__v1__HealthListResponse_msg_init = {
  &grpc_health_v1_HealthListResponse__fields.fields[0],
  16, 1, kUpb_ExtMode_NonExtendable, 1, UPB_FASTTABLE_MASK(255), 0,
#ifdef UPB_TRACING_ENABLED
  "grpc.health.v1.HealthListResponse",
#endif
};

typedef struct {
  upb_MiniTableField fields[2];
  upb_MiniTableSubInternal subs[1];
} grpc__health__v1__HealthListResponse__StatusesEntry_msg_init_Fields;

static const grpc__health__v1__HealthListResponse__StatusesEntry_msg_init_Fields grpc_health_v1_HealthListResponse_StatusesEntry__fields = {{
  {1, 16, 0, kUpb_NoSub, 9, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
  {2, 32, 64, 3, 11, (int)kUpb_FieldMode_Scalar | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
 },
  {
  {.UPB_PRIVATE(submsg) = &grpc__health__v1__HealthCheckResponse_msg_init},
}};

const upb_MiniTable grpc__health__v1__HealthListResponse__StatusesEntry_msg_init = {
  &grpc_health_v1_HealthListResponse_StatusesEntry__fields.fields[0],
  48, 2, kUpb_ExtMode_NonExtendable, 2, UPB_FASTTABLE_MASK(8), 0,
#ifdef UPB_TRACING_ENABLED
  "grpc.health.v1.HealthListResponse.StatusesEntry",
#endif
  UPB_FASTTABLE_INIT({
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x001000003f00000a, &upb_DecodeFast_String_Scalar_Tag1Byte},
  })
};

static const upb_MiniTable *messages_layout[5] = {
  &grpc__health__v1__HealthCheckRequest_msg_init,
  &grpc__health__v1__HealthCheckResponse_msg_init,
  &grpc__health__v1__HealthListRequest_msg_init,
  &grpc__health__v1__HealthListResponse_msg_init,
  &grpc__health__v1__HealthListResponse__StatusesEntry_msg_init,
};

const upb_MiniTableFile grpc_health_v1_health_proto_upb_file_layout = {
  messages_layout,
  NULL,
  NULL,
  5,
  0,
  0,
};

#include "upb/port/undef.inc"

