load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "pgv",
    visibility = ["//visibility:public"],
    runtime_deps = [
        "//java/pgv-java-stub/src/main/java/io/envoyproxy/pgv",
    ],
)
