filegroup(
    name = "build_test_targets",
    srcs = [
        "@grpc",
        "@grpc//:grpc++",
        "@grpc//:grpc++_reflection",
        "@grpc//:grpc++_test",
        "@grpc//:grpc++_unsecure",
        "@grpc//:grpc_opencensus_plugin",
        "@grpc//:grpc_security_base",
        "@grpc//:grpc_unsecure",
        "@grpc//:grpcpp_admin",
        "@grpc//:grpcpp_channelz",
        "@grpc//:grpcpp_csds",
        "@grpc//:grpcpp_orca_service",
        #        "@grpc//examples/protos/...",
    ],
)
