[build-system]
requires = [
    "setuptools>=77.0.1",
    "wheel",
    "Cython==3.1.1",
]
build-backend = "setuptools.build_meta"

[project]
name = "grpcio-observability"
license = "Apache-2.0"
description = "gRPC Python observability package"
readme = {file = "README.rst", content-type = "text/x-rst"} # adding content-type resolves twine check warnings during release upload
authors = [{name = "The gRPC Authors", email = "grpc-io@googlegroups.com"}]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]

dynamic = ["dependencies", "version", "requires-python"]

[project.urls]
Homepage = "https://grpc.io"
"Source Code" = "https://github.com/grpc/grpc/tree/master/src/python/grpcio_observability"
"Bug Tracker" = "https://github.com/grpc/grpc/issues"

[tool.setuptools.packages]
find = {}

[tool.setuptools.dynamic]
version = {attr = "grpc_version.VERSION"}

[tool.setuptools.package-dir]
"" = "."
