[build-system]
requires = [
    "setuptools",
    "wheel",
    "build",
    "cython>=3.1.1",
    "python_version"
]
build-backend = "setuptools.build_meta"

[project]
name = "grpcio-observability"
dynamic = ["version", "dependencies", "requires-python", "readme", "readme-content-type"]
description = "gRPC Python observability package"
authors = [
    {name = "The gRPC Authors", email = "grpc-io@googlegroups.com"}
]
license = {text = "Apache License 2.0"}
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

[project.urls]
Homepage = "https://grpc.io"
"Source Code" = "https://github.com/grpc/grpc/tree/master/src/python/grpcio_observability"
"Bug Tracker" = "https://github.com/grpc/grpc/issues"

[tool.setuptools.dynamic]
version = {attr = "grpc_version.VERSION"}
dependencies = {attr = "setup.install_requires"}
requires-python = {attr = "setup.python_requires"}
readme = {file = "README.rst"}
readme-content-type = {value = "text/x-rst"}
