# TODO: Move to test/distrib/python.

local_repository(
    name = "com_github_grpc_grpc",
    path = "../../../..",
)

# Ensure rules don't rely on __main__ naming convention.
workspace(name = "python_test_repo")

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()

load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")

grpc_extra_deps()

local_repository(
    name = "some_other_repo",
    path = "../python_second_test_repo",
)
