# Copyright 2023 the gRPC authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM debian:13

{% include "../../apt_get_basic.include" %}
{% include "../../run_tests_python_deps_venv.include" %}
{% include "../../cxx_test_deps.include" %}
{% include "../../cxx_deps.include" %}
{% include "../../cmake.include" %}
{% include "../../ccache.include" %}
{% include "../../run_tests_addons.include" %}

# Install openssl 1.1.1 from source
RUN apt-get update && apt-get install -y zlib1g-dev
RUN cd /tmp && \
    wget https://www.openssl.org/source/openssl-1.1.1w.tar.gz && \
    echo "cf3098950cb4d853ad95c0841f1f9c6d3dc102dccfcacd521d93925208b76ac8  openssl-1.1.1w.tar.gz" | sha256sum -c - && \
    tar -xf openssl-1.1.1w.tar.gz && \
    cd openssl-1.1.1w && \
    ./config --prefix=/usr/local/ssl --openssldir=/usr/local/ssl shared zlib && \
    make -j 4 && \
    make install && \
    echo "/usr/local/ssl/lib" > /etc/ld.so.conf.d/openssl-1.1.1.conf && \
    ldconfig && \
    rm -rf /tmp/openssl-1.1.1w*
ENV OPENSSL_ROOT_DIR=/usr/local/ssl

# Define the default command.
CMD ["bash"]
