install! 'cocoapods', :deterministic_uuids => false

# Location of gRPC's repo root relative to this file.
GRPC_LOCAL_SRC = '../../../..'

target 'ConnectivityTestingApp' do
  pod 'gRPC', :path => GRPC_LOCAL_SRC
  pod 'Protobuf', :path => "#{GRPC_LOCAL_SRC}/third_party/protobuf"
  pod 'BoringSSL', :podspec => "#{GRPC_LOCAL_SRC}/src/objective-c"
end
