install! 'cocoapods', :deterministic_uuids => false
platform :ios, '10.0'

# Location of gRPC's repo root relative to this file.
GRPC_LOCAL_SRC = '../../../..'

target 'ConnectivityTestingApp' do
  pod 'gRPC/CFStream', :path => GRPC_LOCAL_SRC
  pod 'gRPC-Core/CFStream-Implementation', :path => GRPC_LOCAL_SRC
  pod 'gRPC-ProtoRPC/CFStream', :path => GRPC_LOCAL_SRC
  pod 'gRPC-RxLibrary', :path => GRPC_LOCAL_SRC
  pod 'Protobuf', :path => "#{GRPC_LOCAL_SRC}/third_party/protobuf"
  pod 'BoringSSL-GRPC', :podspec => "#{GRPC_LOCAL_SRC}/src/objective-c"
end
