%YAML 1.2
--- |
  # Copyright 2021 the gRPC authors.
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
  
  FROM debian:buster
  
  <%include file="../../apt_get_basic.include"/>
  <%include file="../../python_deps.include"/>
  <%include file="../../gcp_api_libraries.include"/>
  <%include file="../../cxx_deps.include"/>
  <%include file="../../cmake.include"/>
  <%include file="../../run_tests_addons.include"/>

  # Install openssl 1.0.2 from source
  RUN apt-get update && apt-get install -y build-essential zlib1g-dev
  RUN cd /tmp && ${"\\"}
      wget https://www.openssl.org/source/old/1.0.2/openssl-1.0.2u.tar.gz && ${"\\"}
      tar -xf openssl-1.0.2u.tar.gz && ${"\\"}
      cd openssl-1.0.2u && ${"\\"}
      ./config --prefix=/usr/local/ssl --openssldir=/usr/local/ssl shared zlib && ${"\\"}
      make -j 4 && ${"\\"}
      make install && ${"\\"}
      rm -rf /tmp/openssl-1.0.2u*
  ENV OPENSSL_ROOT_DIR=/usr/local/ssl

  # Define the default command.
  CMD ["bash"]
