%YAML 1.2
--- |
  # Copyright 2022 The gRPC Authors
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.

  FROM arm64v8/debian:11
  
  <%include file="../../apt_get_basic.include"/>
  <%include file="../../run_tests_addons.include"/>

  # 3.9 is the default python3 version on debian11
  RUN apt-get update && apt-get install -y python3.9 python3.9-dev python3-pip
  
  # for Python test coverage reporting
  RUN python3.9 -m pip install coverage

  # six is required by the run_tests.py test harness
  RUN python3.9 -m pip install six

  <%include file="../../gcp_api_libraries.include"/>

  <%include file="../../cmake.include"/>
  <%include file="../../ccache.include"/>
