%YAML 1.2
--- |
  # Copyright 2015 gRPC authors.
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
  
  FROM alpine:3.15
  
  # Install Git and basic packages.
  RUN apk update && apk add ${'\\'}
    autoconf ${'\\'}
    automake ${'\\'}
    bzip2 ${'\\'}
    build-base ${'\\'}
    cmake ${'\\'}
    ccache ${'\\'}
    curl ${'\\'}
    gcc ${'\\'}
    git ${'\\'}
    libtool ${'\\'}
    linux-headers ${'\\'}
    make ${'\\'}
    perl ${'\\'}
    strace ${'\\'}
    python3 ${'\\'}
    py3-pip ${'\\'}
    unzip ${'\\'}
    wget ${'\\'}
    zip
  
  # use pinned version of pip to avoid sudden breakages
  RUN python3 -m pip install --upgrade pip==19.3.1

  # TODO(jtattermusch): currently six is needed for tools/run_tests scripts
  # but since our python2 usage is deprecated, we should get rid of it.
  RUN python3 -m pip install six==1.16.0

  # Google Cloud Platform API libraries
  # These are needed for uploading test results to BigQuery (e.g. by tools/run_tests scripts)
  RUN python3 -m pip install --upgrade google-auth==1.24.0 google-api-python-client==1.12.8 oauth2client==4.1.0

  RUN python3 -m pip install --upgrade --ignore-installed PyYAML==5.4.1 --user

  <%include file="../../ccache.include"/>
  <%include file="../../run_tests_addons.include"/>
  <%include file="../../git-jenkins.include"/>

  # Define the default command.
  CMD ["bash"]
