# Copyright 2026 gRPC authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM gcc:10

# Install apt-get-install-retry wrapper script
{% include "../../apt_get_install_with_retry.include" %}

RUN /usr/local/bin/apt-get-install-retry curl git time zip

{% include "../../git_avoid_dubious_ownership_error.include" %}
{% include "../../run_tests_python_deps.include" %}
{% include "../../cxx_test_deps.include" %}
{% include "../../cmake.include" %}

# Install ccache 4.2 from official repo.
RUN /usr/local/bin/apt-get-install-retry ccache

{% include "../../run_tests_addons.include" %}

# Define the default command.
CMD ["bash"]
