source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

install! 'cocoapods', :deterministic_uuids => false

target 'RouteGuideClient' do
  # Depend on the generated RouteGuide library.
  pod 'RouteGuide', :path => '.'
end
