/* This file was generated by upbc (the upb compiler) from the input
 * file:
 *
 *     envoy/config/metrics/v2/stats.proto
 *
 * Do not edit -- your changes will be discarded when the file is
 * regenerated. */

#include <stddef.h>
#include "upb/msg_internal.h"
#include "envoy/config/metrics/v2/stats.upb.h"
#include "envoy/api/v2/core/address.upb.h"
#include "envoy/type/matcher/string.upb.h"
#include "google/protobuf/any.upb.h"
#include "google/protobuf/struct.upb.h"
#include "google/protobuf/wrappers.upb.h"
#include "udpa/annotations/status.upb.h"
#include "validate/validate.upb.h"

#include "upb/port_def.inc"

static const upb_msglayout_sub envoy_config_metrics_v2_StatsSink_submsgs[2] = {
  {.submsg = &google_protobuf_Any_msginit},
  {.submsg = &google_protobuf_Struct_msginit},
};

static const upb_msglayout_field envoy_config_metrics_v2_StatsSink__fields[3] = {
  {1, UPB_SIZE(0, 0), 0, 0, 9, _UPB_MODE_SCALAR | (_UPB_REP_STRVIEW << _UPB_REP_SHIFT)},
  {2, UPB_SIZE(8, 16), UPB_SIZE(-13, -25), 1, 11, _UPB_MODE_SCALAR | (_UPB_REP_PTR << _UPB_REP_SHIFT)},
  {3, UPB_SIZE(8, 16), UPB_SIZE(-13, -25), 0, 11, _UPB_MODE_SCALAR | (_UPB_REP_PTR << _UPB_REP_SHIFT)},
};

const upb_msglayout envoy_config_metrics_v2_StatsSink_msginit = {
  &envoy_config_metrics_v2_StatsSink_submsgs[0],
  &envoy_config_metrics_v2_StatsSink__fields[0],
  UPB_SIZE(16, 32), 3, _UPB_MSGEXT_NONE, 3, 255,
};

static const upb_msglayout_sub envoy_config_metrics_v2_StatsConfig_submsgs[3] = {
  {.submsg = &envoy_config_metrics_v2_StatsMatcher_msginit},
  {.submsg = &envoy_config_metrics_v2_TagSpecifier_msginit},
  {.submsg = &google_protobuf_BoolValue_msginit},
};

static const upb_msglayout_field envoy_config_metrics_v2_StatsConfig__fields[3] = {
  {1, UPB_SIZE(12, 24), 0, 1, 11, _UPB_MODE_ARRAY | (_UPB_REP_PTR << _UPB_REP_SHIFT)},
  {2, UPB_SIZE(4, 8), 1, 2, 11, _UPB_MODE_SCALAR | (_UPB_REP_PTR << _UPB_REP_SHIFT)},
  {3, UPB_SIZE(8, 16), 2, 0, 11, _UPB_MODE_SCALAR | (_UPB_REP_PTR << _UPB_REP_SHIFT)},
};

const upb_msglayout envoy_config_metrics_v2_StatsConfig_msginit = {
  &envoy_config_metrics_v2_StatsConfig_submsgs[0],
  &envoy_config_metrics_v2_StatsConfig__fields[0],
  UPB_SIZE(16, 32), 3, _UPB_MSGEXT_NONE, 3, 255,
};

static const upb_msglayout_sub envoy_config_metrics_v2_StatsMatcher_submsgs[1] = {
  {.submsg = &envoy_type_matcher_ListStringMatcher_msginit},
};

static const upb_msglayout_field envoy_config_metrics_v2_StatsMatcher__fields[3] = {
  {1, UPB_SIZE(0, 0), UPB_SIZE(-5, -9), 0, 8, _UPB_MODE_SCALAR | (_UPB_REP_1BYTE << _UPB_REP_SHIFT)},
  {2, UPB_SIZE(0, 0), UPB_SIZE(-5, -9), 0, 11, _UPB_MODE_SCALAR | (_UPB_REP_PTR << _UPB_REP_SHIFT)},
  {3, UPB_SIZE(0, 0), UPB_SIZE(-5, -9), 0, 11, _UPB_MODE_SCALAR | (_UPB_REP_PTR << _UPB_REP_SHIFT)},
};

const upb_msglayout envoy_config_metrics_v2_StatsMatcher_msginit = {
  &envoy_config_metrics_v2_StatsMatcher_submsgs[0],
  &envoy_config_metrics_v2_StatsMatcher__fields[0],
  UPB_SIZE(8, 16), 3, _UPB_MSGEXT_NONE, 3, 255,
};

static const upb_msglayout_field envoy_config_metrics_v2_TagSpecifier__fields[3] = {
  {1, UPB_SIZE(0, 0), 0, 0, 9, _UPB_MODE_SCALAR | (_UPB_REP_STRVIEW << _UPB_REP_SHIFT)},
  {2, UPB_SIZE(8, 16), UPB_SIZE(-17, -33), 0, 9, _UPB_MODE_SCALAR | (_UPB_REP_STRVIEW << _UPB_REP_SHIFT)},
  {3, UPB_SIZE(8, 16), UPB_SIZE(-17, -33), 0, 9, _UPB_MODE_SCALAR | (_UPB_REP_STRVIEW << _UPB_REP_SHIFT)},
};

const upb_msglayout envoy_config_metrics_v2_TagSpecifier_msginit = {
  NULL,
  &envoy_config_metrics_v2_TagSpecifier__fields[0],
  UPB_SIZE(24, 48), 3, _UPB_MSGEXT_NONE, 3, 255,
};

static const upb_msglayout_sub envoy_config_metrics_v2_StatsdSink_submsgs[1] = {
  {.submsg = &envoy_api_v2_core_Address_msginit},
};

static const upb_msglayout_field envoy_config_metrics_v2_StatsdSink__fields[3] = {
  {1, UPB_SIZE(8, 16), UPB_SIZE(-17, -33), 0, 11, _UPB_MODE_SCALAR | (_UPB_REP_PTR << _UPB_REP_SHIFT)},
  {2, UPB_SIZE(8, 16), UPB_SIZE(-17, -33), 0, 9, _UPB_MODE_SCALAR | (_UPB_REP_STRVIEW << _UPB_REP_SHIFT)},
  {3, UPB_SIZE(0, 0), 0, 0, 9, _UPB_MODE_SCALAR | (_UPB_REP_STRVIEW << _UPB_REP_SHIFT)},
};

const upb_msglayout envoy_config_metrics_v2_StatsdSink_msginit = {
  &envoy_config_metrics_v2_StatsdSink_submsgs[0],
  &envoy_config_metrics_v2_StatsdSink__fields[0],
  UPB_SIZE(24, 48), 3, _UPB_MSGEXT_NONE, 3, 255,
};

static const upb_msglayout_sub envoy_config_metrics_v2_DogStatsdSink_submsgs[1] = {
  {.submsg = &envoy_api_v2_core_Address_msginit},
};

static const upb_msglayout_field envoy_config_metrics_v2_DogStatsdSink__fields[2] = {
  {1, UPB_SIZE(8, 16), UPB_SIZE(-13, -25), 0, 11, _UPB_MODE_SCALAR | (_UPB_REP_PTR << _UPB_REP_SHIFT)},
  {3, UPB_SIZE(0, 0), 0, 0, 9, _UPB_MODE_SCALAR | (_UPB_REP_STRVIEW << _UPB_REP_SHIFT)},
};

const upb_msglayout envoy_config_metrics_v2_DogStatsdSink_msginit = {
  &envoy_config_metrics_v2_DogStatsdSink_submsgs[0],
  &envoy_config_metrics_v2_DogStatsdSink__fields[0],
  UPB_SIZE(16, 32), 2, _UPB_MSGEXT_NONE, 1, 255,
};

static const upb_msglayout_field envoy_config_metrics_v2_HystrixSink__fields[1] = {
  {1, UPB_SIZE(0, 0), 0, 0, 3, _UPB_MODE_SCALAR | (_UPB_REP_8BYTE << _UPB_REP_SHIFT)},
};

const upb_msglayout envoy_config_metrics_v2_HystrixSink_msginit = {
  NULL,
  &envoy_config_metrics_v2_HystrixSink__fields[0],
  UPB_SIZE(8, 8), 1, _UPB_MSGEXT_NONE, 1, 255,
};

static const upb_msglayout *messages_layout[7] = {
  &envoy_config_metrics_v2_StatsSink_msginit,
  &envoy_config_metrics_v2_StatsConfig_msginit,
  &envoy_config_metrics_v2_StatsMatcher_msginit,
  &envoy_config_metrics_v2_TagSpecifier_msginit,
  &envoy_config_metrics_v2_StatsdSink_msginit,
  &envoy_config_metrics_v2_DogStatsdSink_msginit,
  &envoy_config_metrics_v2_HystrixSink_msginit,
};

const upb_msglayout_file envoy_config_metrics_v2_stats_proto_upb_file_layout = {
  messages_layout,
  NULL,
  7,
  0,
};

#include "upb/port_undef.inc"

