# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: envoy/extensions/filters/common/jwks/v3/jwks.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'envoy/extensions/filters/common/jwks/v3/jwks.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from envoy.config.core.v3 import base_pb2 as envoy_dot_config_dot_core_dot_v3_dot_base__pb2
from envoy.config.core.v3 import http_uri_pb2 as envoy_dot_config_dot_core_dot_v3_dot_http__uri__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from udpa.annotations import status_pb2 as udpa_dot_annotations_dot_status__pb2
from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2envoy/extensions/filters/common/jwks/v3/jwks.proto\x12\'envoy.extensions.filters.common.jwks.v3\x1a\x1f\x65nvoy/config/core/v3/base.proto\x1a#envoy/config/core/v3/http_uri.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1dudpa/annotations/status.proto\x1a\x17validate/validate.proto\"\x97\x02\n\nRemoteJwks\x12\x39\n\x08http_uri\x18\x01 \x01(\x0b\x32\x1d.envoy.config.core.v3.HttpUriB\x08\xfa\x42\x05\x8a\x01\x02\x10\x01\x12G\n\x0e\x63\x61\x63he_duration\x18\x02 \x01(\x0b\x32\x19.google.protobuf.DurationB\x14\xfa\x42\x11\xaa\x01\x0e\x1a\x06\x08\x80\xb4\xc4\xc3!2\x04\x10\xc0\x84=\x12L\n\x0b\x61sync_fetch\x18\x03 \x01(\x0b\x32\x37.envoy.extensions.filters.common.jwks.v3.JwksAsyncFetch\x12\x37\n\x0cretry_policy\x18\x04 \x01(\x0b\x32!.envoy.config.core.v3.RetryPolicy\"c\n\x0eJwksAsyncFetch\x12\x15\n\rfast_listener\x18\x01 \x01(\x08\x12:\n\x17\x66\x61iled_refetch_duration\x18\x02 \x01(\x0b\x32\x19.google.protobuf.DurationB\xa3\x01\n5io.envoyproxy.envoy.extensions.filters.common.jwks.v3B\tJwksProtoP\x01ZUgithub.com/envoyproxy/go-control-plane/envoy/extensions/filters/common/jwks/v3;jwksv3\xba\x80\xc8\xd1\x06\x02\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'envoy.extensions.filters.common.jwks.v3.jwks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n5io.envoyproxy.envoy.extensions.filters.common.jwks.v3B\tJwksProtoP\001ZUgithub.com/envoyproxy/go-control-plane/envoy/extensions/filters/common/jwks/v3;jwksv3\272\200\310\321\006\002\020\002'
  _globals['_REMOTEJWKS'].fields_by_name['http_uri']._loaded_options = None
  _globals['_REMOTEJWKS'].fields_by_name['http_uri']._serialized_options = b'\372B\005\212\001\002\020\001'
  _globals['_REMOTEJWKS'].fields_by_name['cache_duration']._loaded_options = None
  _globals['_REMOTEJWKS'].fields_by_name['cache_duration']._serialized_options = b'\372B\021\252\001\016\032\006\010\200\264\304\303!2\004\020\300\204='
  _globals['_REMOTEJWKS']._serialized_start=254
  _globals['_REMOTEJWKS']._serialized_end=533
  _globals['_JWKSASYNCFETCH']._serialized_start=535
  _globals['_JWKSASYNCFETCH']._serialized_end=634
# @@protoc_insertion_point(module_scope)
