# Copyright 2016 gRPC authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM --platform=linux/arm64 debian:13

{% include "../../apt_get_basic.include" %}

# Basic python dependencies to be able to run tools/run_tests python scripts
# We install python3-six via apt to avoid pip issues on Debian 13
RUN apt-get update && apt-get install -y \
  python3 \
  python3-pip \
  python3-setuptools \
  python3-yaml \
  python3-six \
  && apt-get clean

# Google Cloud Platform API libraries (inlined from gcp_api_libraries.include)
# We add --break-system-packages since we are not downgrading pip
RUN python3 -m pip install --break-system-packages --upgrade google-auth==1.23.0 google-api-python-client==1.12.8 oauth2client==4.1.0

# Install default PHP (which is 8.4 in Debian 13)
RUN apt-get update && apt-get install -y php php-dev php-pear php-mbstring && apt-get clean

# Install PHPUnit (PHPUnit 11 is the stable version that supports PHP 8.4)
RUN wget https://phar.phpunit.de/phpunit-13.phar && \
    mv phpunit-13.phar /usr/local/bin/phpunit && \
    chmod +x /usr/local/bin/phpunit

{% include "../../php_valgrind.include" %}
{% include "../../cmake.include" %}
RUN apt-get update && apt-get install -y ccache && apt-get clean
{% include "../../run_tests_addons.include" %}

# Define the default command.
CMD ["bash"]

