%YAML 1.2
--- |
  # Copyright 2018 gRPC authors.
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.

  # This is the base Docker image we use for running tests on RBE
  FROM gcr.io/cloud-marketplace/google/rbe-debian8@sha256:1ede2a929b44d629ec5abe86eee6d7ffea1d5a4d247489a8867d46cfde3e38bd

  <%include file="../../apt_get_basic.include"/>
  <%include file="../../gcp_api_libraries.include"/>
  <%include file="../../python_deps.include"/>
  #=================
  # C++ dependencies (purposely excluding Clang because it's part of the base image)
  RUN apt-get update && apt-get -y install libgflags-dev libgtest-dev libc++-dev && apt-get clean

  # Link llvm-symbolizer to where our test scripts expect to find it
  RUN ln -s /usr/local/bin/llvm-symbolizer /usr/bin/llvm-symbolizer

  # Define the default command.
  CMD ["bash"]
