# Copyright 2017 gRPC authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

licenses(["notice"])

exports_files([
    "ca.pem",
    "ca_p256.pem",
    "ca_p384.pem",
    "ca_p521.pem",
    "server0.key",
    "server0.pem",
    "server1.key",
    "server1.pem",
    "server1_p256.key",
    "server1_p256.pem",
    "server1_p384.key",
    "server1_p384.pem",
    "server1_p521.key",
    "server1_p521.pem",
    "client.key",
    "client.pem",
    "client-with-spiffe.key",
    "client-with-spiffe.pem",
    "client_p256.key",
    "client_p256.pem",
    "client_p384.key",
    "client_p384.pem",
    "client_p521.key",
    "client_p521.pem",
    "badserver.key",
    "badserver.pem",
    "badclient.key",
    "badclient.pem",
    "multi-domain.key",
    "multi-domain.pem",
    "leaf_signed_by_intermediate.key",
    "leaf_and_intermediate_chain.pem",
])
