%YAML 1.2
--- |
  # Copyright 2021 gRPC authors.
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
  
  FROM silkeh/clang:15-bullseye
  
  RUN apt-get update && apt-get install -y build-essential curl git time wget zip && apt-get clean
  <%include file="../../run_tests_python_deps.include"/>
  <%include file="../../cmake.include"/>
  <%include file="../../ccache.include"/>
  <%include file="../../run_tests_addons.include"/>
  <%include file="../../git-jenkins.include"/>

  # Define the default command.
  CMD ["bash"]
