# Copyright 2021 gRPC authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

licenses(["notice"])

exports_files([
    "ca.pem",
    "revoked.key",
    "revoked.pem",
    "valid.key",
    "valid.pem",
    "leaf_signed_by_intermediate.key",
    "leaf_signed_by_intermediate.pem",
    "leaf_and_intermediate_chain.pem",
    "intermediate_ca.key",
    "intermediate_ca.pem",
])
