/* This file was generated by upbc (the upb compiler) from the input
 * file:
 *
 *     envoy/api/v2/listener/udp_listener_config.proto
 *
 * Do not edit -- your changes will be discarded when the file is
 * regenerated. */

#include "upb/def.h"

extern upb_def_init google_protobuf_any_proto_upbdefinit;
extern upb_def_init google_protobuf_struct_proto_upbdefinit;
extern const upb_msglayout envoy_api_v2_listener_UdpListenerConfig_msginit;

static const upb_msglayout *layouts[1] = {
  &envoy_api_v2_listener_UdpListenerConfig_msginit,
};

static const char descriptor[445] =
  "\n/envoy/api/v2/listener/udp_listener_con"
  "fig.proto\022\025envoy.api.v2.listener\032\031google"
  "/protobuf/any.proto\032\034google/protobuf/str"
  "uct.proto\"\274\001\n\021UdpListenerConfig\022*\n\021udp_l"
  "istener_name\030\001 \001(\tR\017udpListenerName\0221\n\006c"
  "onfig\030\002 \001(\0132\027.google.protobuf.StructH\000R\006"
  "config\0229\n\014typed_config\030\003 \001(\0132\024.google.pr"
  "otobuf.AnyH\000R\013typedConfigB\r\n\013config_type"
  "Bs\n#io.envoyproxy.envoy.api.v2.listenerB"
  "\026UdpListenerConfigProtoP\001\252\002\027Envoy.Api.V2"
  ".ListenerNS\352\002\027Envoy.Api.V2.ListenerNSb\006p"
  "roto3";

static upb_def_init *deps[3] = {
  &google_protobuf_any_proto_upbdefinit,
  &google_protobuf_struct_proto_upbdefinit,
  NULL
};

upb_def_init envoy_api_v2_listener_udp_listener_config_proto_upbdefinit = {
  deps,
  layouts,
  "envoy/api/v2/listener/udp_listener_config.proto",
  UPB_STRVIEW_INIT(descriptor, 445)
};
