%YAML 1.2
--- |
  # Copyright 2018 The gRPC Authors
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.

  <%include file="../../python_stretch.include"/>

  RUN apt-get update && apt-get install -y zlib1g-dev libssl-dev
  RUN apt-get update && apt-get install -y jq build-essential libffi-dev

  RUN cd /tmp && ${'\\'}
    wget -q https://www.python.org/ftp/python/3.6.9/Python-3.6.9.tgz && ${'\\'}
    tar xzvf Python-3.6.9.tgz && ${'\\'}
    cd Python-3.6.9 && ${'\\'}
    ./configure && ${'\\'}
    make install
  
  RUN cd /tmp && ${'\\'}
    echo "ff7cdaef4846c89c1ec0d7b709bbd54d Python-3.6.9.tgz" > checksum.md5 && ${'\\'}
    md5sum -c checksum.md5

  RUN apt-get update && apt-get -t buster install -y python3.7 python3-all-dev
  RUN curl https://bootstrap.pypa.io/get-pip.py | python3.7

  # for Python test coverage reporting
  RUN python3.7 -m pip install coverage

  RUN python3.6 -m ensurepip && ${'\\'}
      python3.6 -m pip install coverage
