option(gRPC_MSVC_DISABLE_DEPRECATION_WARNINGS "Disable MSVC CRT and WINSOCK deprecation warnings" OFF)

if(gRPC_MSVC_DISABLE_DEPRECATION_WARNINGS)
    add_definitions(-D_CRT_SECURE_NO_WARNINGS -D_WINSOCK_DEPRECATED_NO_WARNINGS)
endif()
