%YAML 1.2
--- |
  # Copyright 2021 The gRPC Authors
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
  
  <%include file="../../oss_fuzz_base.include"/>
  <%include file="../../bazel.include"/>

  #========================
  # Java
  RUN apt-get install -y openjdk-21-jdk

  #========================
  # Android SDK/NDK installation
  ENV ANDROID_SDK_VERSION 11076708
  ENV ANDROID_NDK_VERSION 26.2.11394342

  ENV SDK_ROOT /opt/android-sdk

  RUN mkdir -p $SDK_ROOT
  RUN cd $SDK_ROOT && \
      wget -O cmd.zip https://dl.google.com/android/repository/commandlinetools-linux-${'${ANDROID_SDK_VERSION}'}_latest.zip && \
      unzip -q cmd.zip && \
      rm cmd.zip

  RUN yes | $SDK_ROOT/cmdline-tools/bin/sdkmanager --sdk_root=$SDK_ROOT --licenses  # accept all licenses

  # This is not required but desirable to reduce the time to download and the chance of download failure.
  RUN mkdir -p ~/.android && touch ~/.android/repositories.cfg

  RUN $SDK_ROOT/cmdline-tools/bin/sdkmanager --sdk_root=$SDK_ROOT "ndk;$ANDROID_NDK_VERSION" "platforms;android-33" "build-tools;34.0.0"

  # Set environment variables for Bazel rules
  ENV ANDROID_HOME $SDK_ROOT
  ENV ANDROID_NDK_HOME $SDK_ROOT/ndk/$ANDROID_NDK_VERSION
  
  # Define the default command.
  CMD ["bash"]
