%YAML 1.2
--- |
  # Copyright 2021 The gRPC Authors
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
  
  <%include file="../../oss_fuzz_base.include"/>
  <%include file="../../bazel.include"/>

  #========================
  # Java
  RUN apt-get install -y openjdk-8-jdk

  #========================
  # Android SDK/NDK installation
  ENV SDK_ROOT=/opt/android-sdk
  RUN mkdir -p $SDK_ROOT
  RUN wget -O cmd.zip dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip && \
      unzip cmd.zip && rm cmd.zip && \
      yes | ./cmdline-tools/bin/sdkmanager --sdk_root=$SDK_ROOT 'tools' && \
      yes | ./cmdline-tools/bin/sdkmanager --sdk_root=$SDK_ROOT 'platform-tools' && \
      yes | ./cmdline-tools/bin/sdkmanager --sdk_root=$SDK_ROOT 'build-tools;30.0.3' && \
      yes | ./cmdline-tools/bin/sdkmanager --sdk_root=$SDK_ROOT 'platforms;android-29' && \
      yes | ./cmdline-tools/bin/sdkmanager --sdk_root=$SDK_ROOT 'ndk-bundle' && \
      yes | ./cmdline-tools/bin/sdkmanager --sdk_root=$SDK_ROOT 'ndk;21.4.7075529'

  # Set environment variables for Bazel rules
  ENV ANDROID_HOME=/opt/android-sdk
  ENV ANDROID_NDK_HOME=/opt/android-sdk/ndk/21.4.7075529
  
  RUN mkdir -p /var/local/jenkins
  
  # Define the default command.
  CMD ["bash"]
