from typing import Any

EOF: Any

class BaseError(Exception): ...
class UsageError(BaseError): ...
class InternalError(BaseError): ...
class AbortError(BaseError): ...

def build_census_context() -> Any: ...
def init_grpc_aio() -> None: ...
def shutdown_grpc_aio() -> None: ...

class CallCredentials: ...
class ChannelCredentials: ...

class AioRpcStatus(Exception):
    def __init__(
        self,
        code: int,
        details: str,
        trailing_metadata: tuple | None,
        debug_error_string: str | None,
    ) -> None: ...
    def code(self) -> int: ...
    def details(self) -> str: ...
    def trailing_metadata(self) -> tuple: ...
    def debug_error_string(self) -> str: ...

class ChannelArgKey:
    enable_census: Any
    max_concurrent_streams: Any
    max_receive_message_length: Any
    max_send_message_length: Any
    http2_initial_sequence_number: Any
    default_authority: Any
    primary_user_agent_string: Any
    secondary_user_agent_string: Any
    ssl_session_cache: Any
    ssl_target_name_override: Any

def get_working_loop() -> Any: ...
def schedule_coro_threadsafe(coro: Any, loop: Any) -> Any: ...

class AioChannel:
    target: bytes
    def __init__(
        self,
        target: bytes,
        options: tuple,
        credentials: ChannelCredentials | None,
        loop: Any,
    ) -> None: ...
    def call(
        self,
        method: bytes,
        deadline: float | None,
        python_call_credentials: Any,
        wait_for_ready: bool | None,
    ) -> _AioCall: ...
    def check_connectivity_state(self, try_to_connect: bool) -> int: ...
    async def watch_connectivity_state(
        self,
        last_observed_state: int,
        deadline: float | None,
    ) -> bool: ...
    def closing(self) -> None: ...
    def close(self) -> None: ...
    def closed(self) -> bool: ...

class _AioCall:
    _initial_metadata: tuple
    _status: AioRpcStatus
    def __init__(
        self,
        channel: AioChannel,
        deadline: float | None,
        method: bytes,
        call_credentials: CallCredentials | None,
        wait_for_ready: bool | None,
    ) -> None: ...
    def add_done_callback(self, callback: Any) -> None: ...
    def time_remaining(self) -> float | None: ...
    def cancel(self, details: str) -> None: ...
    def done(self) -> bool: ...
    def cancelled(self) -> bool: ...
    async def status(self) -> AioRpcStatus: ...
    def is_ok(self) -> bool: ...
    async def initial_metadata(self) -> tuple: ...
    def is_locally_cancelled(self) -> bool: ...
    def set_internal_error(self, error_str: str) -> None: ...
    async def unary_unary(
        self,
        request: bytes,
        outbound_initial_metadata: tuple,
        context: Any | None = ...,
    ) -> bytes: ...
    async def receive_serialized_message(self) -> Any: ...
    async def send_serialized_message(self, message: bytes) -> None: ...
    async def send_receive_close(self) -> None: ...
    async def initiate_unary_stream(
        self,
        request: bytes,
        outbound_initial_metadata: tuple,
        context: Any | None = ...,
    ) -> None: ...
    async def stream_unary(
        self,
        outbound_initial_metadata: tuple,
        metadata_sent_observer: Any,
        context: Any | None = ...,
    ) -> bytes: ...
    async def initiate_stream_stream(
        self,
        outbound_initial_metadata: tuple,
        metadata_sent_observer: Any,
        context: Any | None = ...,
    ) -> None: ...

class AioServer:
    def __init__(
        self,
        loop: Any,
        thread_pool: Any,
        generic_handlers: Any,
        interceptors: Any,
        options: Any,
        maximum_concurrent_rpcs: int | None,
    ) -> None: ...
    def add_generic_rpc_handlers(self, generic_rpc_handlers: Any) -> None: ...
    def add_insecure_port(self, address: Any) -> int: ...
    def add_secure_port(self, address: Any, server_credentials: Any) -> int: ...
    async def start(self) -> None: ...
    async def shutdown(self, grace: float | None) -> None: ...
    async def wait_for_termination(self, timeout: float | None) -> bool: ...
    def is_running(self) -> bool: ...
