from typing import Any

# Module Level Constants
EOF: Any

# Base Exceptions
class BaseError(Exception): ...
class UsageError(BaseError): ...
class InternalError(BaseError): ...
class AbortError(BaseError): ...

# Core Classes
class CallCredentials: ...
class ChannelCredentials: ...

class CallDetails:
    method: bytes
    host: bytes
    deadline: float

class Call:
    def start_client_batch(self, operations: Any, tag: Any) -> Any: ...
    def start_server_batch(self, operations: Any, tag: Any) -> Any: ...
    def cancel(self, error_code: Any = ..., details: Any = ...) -> Any: ...
    def set_credentials(self, call_credentials: Any) -> Any: ...
    def peer(self) -> bytes: ...

# Module Level Functions using Call
def build_census_context() -> Any: ...
def init_grpc_aio() -> None: ...
def shutdown_grpc_aio() -> None: ...
def get_working_loop() -> Any: ...
def schedule_coro_threadsafe(coro: Any, loop: Any) -> Any: ...
def peer_identities(call: Call) -> Any: ...
def peer_identity_key(call: Call) -> Any: ...
def auth_context(call: Call) -> Any: ...
def install_context_from_request_call_event(event: Any) -> Any: ...
def uninstall_context() -> Any: ...

# Event Classes
class BaseEvent:
    completion_type: Any
    success: bool
    tag: Any
    call: Call
    call_details: CallDetails
    invocation_metadata: tuple
    batch_operations: Any

class ConnectivityEvent(BaseEvent): ...
class RequestCallEvent(BaseEvent): ...
class BatchOperationEvent(BaseEvent): ...
class ServerShutdownEvent(BaseEvent): ...

class CompletionQueue:
    is_shutting_down: bool
    is_shutdown: bool
    def __init__(self, shutdown_cq: bool = ...) -> None: ...
    def poll(self, deadline: float | None = ...) -> BaseEvent: ...
    def shutdown(self) -> None: ...
    def clear(self) -> None: ...

class Server:
    def __init__(self, arguments: Any, xds: bool) -> None: ...
    def request_call(self, call_queue: CompletionQueue, server_queue: CompletionQueue, tag: Any) -> Any: ...
    def request_registered_call(self, call_queue: CompletionQueue, server_queue: CompletionQueue, method: str, tag: Any) -> Any: ...
    def register_completion_queue(self, queue: CompletionQueue) -> None: ...
    def register_method(self, fully_qualified_method: str) -> None: ...
    def start(self, backup_queue: bool = ...) -> None: ...
    def add_http2_port(self, address: bytes, server_credentials: Any = ...) -> int: ...
    def shutdown(self, queue: CompletionQueue, tag: Any) -> None: ...
    def cancel_all_calls(self) -> None: ...
    def destroy(self) -> None: ...

# Operation Classes
class Operation:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def initial_metadata(self) -> Any: ...
    def message(self) -> bytes | None: ...
    def trailing_metadata(self) -> Any: ...
    def code(self) -> Any: ...
    def details(self) -> str: ...
    def error_string(self) -> str: ...
    def cancelled(self) -> bool: ...

SendInitialMetadataOperation = Operation
SendMessageOperation = Operation
SendCloseFromClientOperation = Operation
SendStatusFromServerOperation = Operation
ReceiveInitialMetadataOperation = Operation
ReceiveMessageOperation = Operation
ReceiveStatusOnClientOperation = Operation
ReceiveCloseOnServerOperation = Operation

# Enums/Attributes/Records
class ChannelArgKey:
    enable_census: Any
    max_concurrent_streams: Any
    max_receive_message_length: Any
    max_send_message_length: Any
    http2_initial_sequence_number: Any
    default_authority: Any
    primary_user_agent_string: Any
    secondary_user_agent_string: Any
    ssl_session_cache: Any
    ssl_target_name_override: Any

class ConnectivityState:
    idle: Any
    connecting: Any
    ready: Any
    transient_failure: Any
    shutdown: Any

class WriteFlag:
    buffer_hint: Any
    no_compress: Any

class StatusCode:
    ok: Any
    cancelled: Any
    unknown: Any
    invalid_argument: Any
    deadline_exceeded: Any
    not_found: Any
    already_exists: Any
    permission_denied: Any
    unauthenticated: Any
    resource_exhausted: Any
    failed_precondition: Any
    aborted: Any
    out_of_range: Any
    unimplemented: Any
    internal: Any
    unavailable: Any
    data_loss: Any

class CallError:
    ok: Any
    error: Any
    not_on_server: Any
    not_on_client: Any
    already_accepted: Any
    already_invoked: Any
    not_invoked: Any
    already_finished: Any
    too_many_operations: Any
    invalid_flags: Any
    invalid_metadata: Any

class CompletionType:
    queue_shutdown: Any
    queue_timeout: Any
    operation_complete: Any

# AsyncIO Stack Classes
class AioRpcStatus(Exception):
    def __init__(
        self,
        code: int,
        details: str,
        trailing_metadata: tuple | None,
        debug_error_string: str | None,
    ) -> None: ...
    def code(self) -> int: ...
    def details(self) -> str: ...
    def trailing_metadata(self) -> tuple: ...
    def debug_error_string(self) -> str: ...

class AioChannel:
    target: bytes
    def __init__(
        self,
        target: bytes,
        options: tuple,
        credentials: ChannelCredentials | None,
        loop: Any,
    ) -> None: ...
    def call(
        self,
        method: bytes,
        deadline: float | None,
        python_call_credentials: Any,
        wait_for_ready: bool | None,
    ) -> _AioCall: ...
    def check_connectivity_state(self, try_to_connect: bool) -> int: ...
    async def watch_connectivity_state(
        self,
        last_observed_state: int,
        deadline: float | None,
    ) -> bool: ...
    def closing(self) -> None: ...
    def close(self) -> None: ...
    def closed(self) -> bool: ...

class _AioCall:
    _initial_metadata: tuple
    _status: AioRpcStatus
    def __init__(
        self,
        channel: AioChannel,
        deadline: float | None,
        method: bytes,
        call_credentials: CallCredentials | None,
        wait_for_ready: bool | None,
    ) -> None: ...
    def add_done_callback(self, callback: Any) -> None: ...
    def time_remaining(self) -> float | None: ...
    def cancel(self, details: str) -> None: ...
    def done(self) -> bool: ...
    def cancelled(self) -> bool: ...
    async def status(self) -> AioRpcStatus: ...
    def is_ok(self) -> bool: ...
    async def initial_metadata(self) -> tuple: ...
    def is_locally_cancelled(self) -> bool: ...
    def set_internal_error(self, error_str: str) -> None: ...
    async def unary_unary(
        self,
        request: bytes,
        outbound_initial_metadata: tuple,
        context: Any | None = ...,
    ) -> bytes: ...
    async def receive_serialized_message(self) -> Any: ...
    async def send_serialized_message(self, message: bytes) -> None: ...
    async def send_receive_close(self) -> None: ...
    async def initiate_unary_stream(
        self,
        request: bytes,
        outbound_initial_metadata: tuple,
        context: Any | None = ...,
    ) -> None: ...
    async def stream_unary(
        self,
        outbound_initial_metadata: tuple,
        metadata_sent_observer: Any,
        context: Any | None = ...,
    ) -> bytes: ...
    async def initiate_stream_stream(
        self,
        outbound_initial_metadata: tuple,
        metadata_sent_observer: Any,
        context: Any | None = ...,
    ) -> None: ...

class AioServer:
    def __init__(
        self,
        loop: Any,
        thread_pool: Any,
        generic_handlers: Any,
        interceptors: Any,
        options: Any,
        maximum_concurrent_rpcs: int | None,
    ) -> None: ...
    def add_generic_rpc_handlers(self, generic_rpc_handlers: Any) -> None: ...
    def add_insecure_port(self, address: Any) -> int: ...
    def add_secure_port(self, address: Any, server_credentials: Any) -> int: ...
    async def start(self) -> None: ...
    async def shutdown(self, grace: float | None) -> None: ...
    async def wait_for_termination(self, timeout: float | None) -> bool: ...
    def is_running(self) -> bool: ...
