%YAML 1.2
--- |
  # Copyright 2018 The gRPC authors
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
  
  FROM debian:stretch
  
  <%include file="../../apt_get_basic.include"/>
  <%include file="../../gcp_api_libraries.include"/>
  <%include file="../../apt_get_python_27.include"/>
  <%include file="../../debian_testing_repo.include"/>

  RUN apt-get update && apt-get -t testing install -y python3.7 python3-all-dev
  RUN curl https://bootstrap.pypa.io/get-pip.py | python3.7

  <%include file="../../run_tests_addons.include"/>
  # Define the default command.
  CMD ["bash"]
