# Copyright 2025 gRPC authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

package(features = [
    "layering_check",
    "parse_headers",
])

licenses(["notice"])

exports_files([
    "ca.key",
    "ca.pem",
    "client.key",
    "client_spiffebundle.json",
    "client_spiffe.pem",
    "intermediate_ca.key",
    "intermediate_ca.pem",
    "intermediate.cnf",
    "intermediate_gen.sh",
    "invalid_utf8_san.key",
    "invalid_utf8_san_spiffe.pem",
    "leaf_and_intermediate_chain.pem",
    "leaf_signed_by_intermediate.key",
    "leaf_signed_by_intermediate.pem",
    "multi_san.key",
    "multi_san_spiffe.pem",
    "server.key",
    "server_spiffebundle.json",
    "server_spiffe.pem",
])
