%YAML 1.2
--- |
  # Copyright 2015 gRPC authors.
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
  
  # Pinned version of the base image is used to avoid regressions caused
  # by rebuilding of this docker image. To see available versions, you can run
  # "gcloud container images list-tags gcr.io/oss-fuzz-base/base-builder"
  # Image(c7f1523ebd92) is built on Jul 29, 2021
  FROM gcr.io/oss-fuzz-base/base-builder@sha256:c7f1523ebd9234b9ff57e5240f8c06569143373be019c92f1e6df18a1e048f37
  
  # -------------------------- WARNING --------------------------------------
  # If you are making changes to this file, consider changing
  # https://github.com/google/oss-fuzz/blob/master/projects/grpc/Dockerfile
  # accordingly.
  # -------------------------------------------------------------------------

  # Install basic packages and Bazel dependencies.
  RUN apt-get update && apt-get install -y software-properties-common python-software-properties
  RUN add-apt-repository ppa:webupd8team/java
  RUN apt-get update && apt-get -y install ${'\\'}
    autoconf ${'\\'}
    build-essential ${'\\'}
    curl ${'\\'}
    wget ${'\\'}
    libtool ${'\\'}
    make ${'\\'}
    openjdk-8-jdk ${'\\'}
    vim
  
  #====================
  # Python dependencies

  # Install dependencies
  RUN apt-get update && apt-get install -y ${'\\'}
      python-all-dev ${'\\'}
      python3-all-dev ${'\\'}
      python-setuptools

  <%include file="../../compile_python_36.include"/>

  <%include file="../../bazel.include"/>
  
  RUN mkdir -p /var/local/jenkins
  
  # Define the default command.
  CMD ["bash"]
