HHVM_EXTENSION(grpc ext/grpc/byte_buffer.h)
HHVM_EXTENSION(grpc ext/grpc/call.h)
HHVM_EXTENSION(grpc ext/grpc/call_credentials.h)
HHVM_EXTENSION(grpc ext/grpc/channel.h)
HHVM_EXTENSION(grpc ext/grpc/channel_credentials.h)
HHVM_EXTENSION(grpc ext/grpc/completion_queue.h)
HHVM_EXTENSION(grpc ext/grpc/hhvm_grpc.h)
HHVM_EXTENSION(grpc ext/grpc/server.h)
HHVM_EXTENSION(grpc ext/grpc/server_credentials.h)
HHVM_EXTENSION(grpc ext/grpc/timeval.h)
HHVM_EXTENSION(grpc ext/grpc/version.h)

HHVM_EXTENSION(grpc ext/grpc/byte_buffer.cpp)
HHVM_EXTENSION(grpc ext/grpc/call.cpp)
HHVM_EXTENSION(grpc ext/grpc/call_credentials.cpp)
HHVM_EXTENSION(grpc ext/grpc/channel.cpp)
HHVM_EXTENSION(grpc ext/grpc/channel_credentials.cpp)
HHVM_EXTENSION(grpc ext/grpc/completion_queue.cpp)
HHVM_EXTENSION(grpc ext/grpc/hhvm_grpc.cpp)
HHVM_EXTENSION(grpc ext/grpc/server.cpp)
HHVM_EXTENSION(grpc ext/grpc/server_credentials.cpp)
HHVM_EXTENSION(grpc ext/grpc/timeval.cpp)

HHVM_SYSTEMLIB(grpc ext/grpc/call.php)
HHVM_SYSTEMLIB(grpc ext/grpc/call_credentials.php)
HHVM_SYSTEMLIB(grpc ext/grpc/channel.php)
HHVM_SYSTEMLIB(grpc ext/grpc/channel_credentials.php)
HHVM_SYSTEMLIB(grpc ext/grpc/server.php)
HHVM_SYSTEMLIB(grpc ext/grpc/server_credentials.php)
HHVM_SYSTEMLIB(grpc ext/grpc/timeval.php)
HHVM_SYSTEMLIB(grpc lib/Grpc/AbstractCall.php)
HHVM_SYSTEMLIB(grpc lib/Grpc/BaseStub.php)
HHVM_SYSTEMLIB(grpc lib/Grpc/BidiStreamingCall.php)
HHVM_SYSTEMLIB(grpc lib/Grpc/ClientStreamingCall.php)
HHVM_SYSTEMLIB(grpc lib/Grpc/ServerStreamingCall.php)
HHVM_SYSTEMLIB(grpc lib/Grpc/UnaryCall.php)
 
