---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  namespace: ${namespace_name}
  name: ${pod_monitoring_name}
  labels:
    owner: xds-k8s-interop-test
spec:
  selector:
    matchLabels:
      deployment_id: ${deployment_id}
  endpoints:
  - port: 9464
    interval: 10s
