name: Build Python Wheel for win_arm64

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build_wheels:
    name: Build wheel for ${{ matrix.python[0] }}-${{ matrix.buildplat[1] }}
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      fail-fast: false
      matrix:
        buildplat:
          - ["windows-11-arm", "win_arm64"]
        python: [["cp311", "3.11"], ["cp312", "3.12"], ["cp313", "3.13"]]

    steps:
      - name: Checkout grpc
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.3
        env:
          CIBW_BUILD: ${{ matrix.python[0] }}-${{ matrix.buildplat[1] }}
          CIBW_BUILD_FRONTEND: 'pip'
          CIBW_PLATFORM: 'windows'
          CIBW_ARCHS: 'ARM64'

      - name: Validate wheel RECORD
        shell: bash -el {0}
        run: |
          python -m pip install wheel
          for whl in $(ls wheelhouse); do wheel unpack wheelhouse/$whl -d /tmp; done

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.python[0] }}-${{ matrix.buildplat[1] }} # Artifact name like "cp312-win_arm64"
          path: ./wheelhouse/*.whl
