# This is a basic workflow to help you get started with Actions

name: build gRPC ubuntu16.04

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install:
    name: set up env
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Checkout
        uses: ./
        with:
          grpc-version: v1.30.2

      - name: update libs
        env:
          MY_VAR: My test
        run: |
          echo $MY_VAR
          echo Install 1,
          echo $PATH
          sudo apt-get install build-essential autoconf libtool pkg-config
          sudo apt-get install cmake
          sudo apt-get install libgflags-dev
          sudo apt-get install clang-5.0 libc++-dev
          
      - name: Verify gRPC
        run: |
          svn export https://github.com/grpc/grpc/tags/v1.30.2  
          
      - name: Submodule update --init
        run: |
          echo Submodule update --init
          echo $PATH
          cd grpc
          git submodule update --init
          
      - name: build start
        run: |
          echo build start:$PATH
          mkdir -p cmake/build
          cd cmake/build
          cmake ../..
          make
